### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/sinais_vitais_excluir.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#224]
Vulnerability Analysis
1. A função `permissao($_SESSION['id_pessoa'], 11, 7);` é chamada, mas a sua implementação não está presente no código fornecido.

2. Falta importar a classe PDO no código, o que pode resultar em um erro de "class not found". O correto seria adicionar o seguinte trecho no início do arquivo:

```php
use PDO;
```

3. A mensagem de erro exibida no bloco `catch` está retornando a exceção diretamente, o que pode não ser adequado por questões de segurança, pois a mensagem de erro pode conter informações sensíveis sobre o banco de dados. É recomendável tratar a exceção de forma mais genérica, sem exibir detalhes específicos para o usuário final.

4. A linha `$pdo = null;` no bloco `finally` tenta atribuir `null` à variável de conexão `$pdo`, o que pode resultar em erro caso a conexão ainda esteja ativa. Não é necessário atribuir `null` à conexão, já que ela será fechada automaticamente ao final do bloco `try`.

5. É importante lembrar de sanitizar ou validar os dados recebidos por POST, como no caso do parâmetro `$_POST["id_sinais_vitais"]`, para evitar possíveis ataques de SQL Injection.

6. Não está sendo feita a verificação se o parâmetro `id_sinais_vitais` foi enviado no POST antes de utilizar, o que pode resultar em erro caso o valor não esteja presente. Recomenda-se realizar essa verificação para garantir a integridade dos dados.

7. A falta de mensagens de erro específicas para cada tipo de exceção que possa ocorrer pode dificultar a identificação e resolução de problemas durante a execução do código.

Essas são algumas vulnerabilidades e melhorias que podem ser feitas no código fornecido para torná-lo mais seguro e robusto.

**Comment by FlameOff** [comment]
Corrigido os erros
