### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/intercorrencia_visualizar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#229]
Vulnerability Analysis
A vulnerabilidade encontrada no código é a injeção de SQL no trecho que realiza a consulta no banco de dados. Esta vulnerabilidade pode ser explorada caso um usuário mal-intencionado consiga manipular os dados enviados para a aplicação, o que poderia resultar na execução de comandos SQL maliciosos.

No trecho de código a seguir, há a concatenação direta do valor da variável `$id_pessoa` na query SQL:
```php
$resultado = mysqli_query($conexao, "SELECT * FROM funcionario WHERE id_pessoa=$id_pessoa");
```
Para corrigir essa vulnerabilidade, é recomendado utilizar prepared statements para proteger as consultas SQL contra a injeção de SQL. Com a utilização de prepared statements, os valores dos parâmetros são passados separadamente das instruções SQL, prevenindo assim a possibilidade de injeção de código.

Além disso, é importante escapar os dados antes de inseri-los em uma consulta SQL. No caso de consultas diretas, é possível usar `mysqli_real_escape_string()`. Porém, a abordagem de prepared statements é mais segura e eficaz.

Além disso, é importante validar a entrada do usuário para garantir que apenas dados válidos sejam utilizados na consulta SQL.

Sugiro aplicar as correções necessárias para proteger o código contra injeção de SQL.

**Comment by FlameOff** [comment]
Aplicado a opção mysqli_real_escape_string(), caso necessário, verificar as linhas 26 e 27 do código onde foi aplicado as mudanças
