### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/historico_paciente.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#231]
Vulnerability Analysis
1. **Uso de extract($_REQUEST):** O uso da função `extract()` é considerado uma prática insegura, pois ela extrai variáveis ​​do array de requisição diretamente para o escopo global do script. Isso pode resultar em problemas de segurança, como a sobreposição de variáveis ​​existentes ou a criação acidental de novas variáveis. É recomendado evitar o uso dessa função e optar por acessar as variáveis diretamente no array de requisição ($_GET, $_POST, $_COOKIE).

2. **Concatenação de SQL:** No trecho de código onde é feita a consulta SQL, há uma concatenação diretamente na string da consulta, o que pode abrir caminho para ataques de injeção de SQL. Recomenda-se utilizar prepared statements e placeholders para evitar esse tipo de vulnerabilidade.

```php
$resultado = mysqli_query($conexao, "SELECT * FROM funcionario WHERE id_pessoa=$id_pessoa");
```

3. **Acesso ao Banco de Dados:** Há uma combinação de duas extensões de acesso ao banco de dados, `mysqli` e `PDO`, que não é recomendada. O código mistura funções do `mysqli` (como `mysqli_query`) e do `PDO` (como `prepare` e `fetchAll`). É mais seguro e recomendado escolher uma extensão única para o acesso ao banco de dados em todo o projeto.

4. **Manipulação de Erros com True/False:** No trecho de código que verifica se a consulta ao banco de dados foi bem-sucedida ou não, é utilizado `is_null` e `is_bool`. Essas funções não são adequadas para verificar resultados de consultas em banco de dados. Recomenda-se utilizar métodos apropriados para verificar se a consulta retornou resultados válidos.

5. **Redirecionamentos sem Escape:** Os redirecionamentos realizados com a função `header` não estão sendo feitos de forma segura, pois não há escape adequado nos parâmetros utilizados na URL de redirecionamento. Isso pode levar a vulnerabilidades de redirecionamento aberto (open redirect). Sempre valide e escape as URLs antes de utilizá-las em redirecionamentos.

Essas são algumas vulnerabilidades e boas práticas que precisam ser consideradas e corrigidas no código apresentado.

**Comment by nilsonLazarin** [comment]
@FlameOff, vulnerabilidade parece ter persistido.
@mustafaneto,
Vulnerabilidade relatada: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-f654-c5r5-jx77
