### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/exibir_alergia.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#235]
Vulnerability Analysis
A vulnerabilidade presente no código é a falta de tratamento de possíveis erros de conexão com o banco de dados. Caso a conexão não seja estabelecida corretamente, o código irá gerar um erro fatal que exporá informações sensíveis, como dados de conexão no arquivo Conexao.php.

Para corrigir essa vulnerabilidade, é recomendado adicionar tratamento de erros para a conexão com o banco de dados. Por exemplo, podem ser utilizadas instruções try-catch para capturar exceções e lidar com elas de forma adequada. Além disso, é importante também implementar práticas de segurança como não expor informações sensíveis no código fonte e configurar corretamente as permissões de acesso aos arquivos.

**Comment by FlameOff** [comment]
Colocado um try para o código e um catch (PDOException $varíavel_de_erro)
