### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/atendmedico_upload.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#244]
Vulnerability Analysis
1. A primeira vulnerabilidade está na linha:
```php
$teste = $pdo->query("SELECT id_funcionario FROM pessoa p JOIN funcionario f ON(p.id_pessoa = f.id_pessoa) WHERE f.id_pessoa = " .$_SESSION['id_pessoa'])->fetchAll(PDO::FETCH_ASSOC);
```
O código está diretamente inserindo o valor de `$_SESSION['id_pessoa']` na consulta SQL sem qualquer tipo de validação, tornando suscetível a ataques de injeção de SQL.

A solução para essa vulnerabilidade seria utilizar prepared statements para evitar a injeção de SQL. Além disso, é importante realizar a validação e sanitização dos dados antes de utilizá-los em consultas SQL.

2. Outra vulnerabilidade é a utilização de `extract($_REQUEST);`, que pode expor variáveis não desejadas e levar a possíveis conflitos de variáveis. É recomendado evitar o uso dessa função devido aos riscos de segurança associados a ela. Em vez disso, é melhor acessar os valores de `$_REQUEST` diretamente.

3. Na linha:
```php
$obj_post = $_POST['acervo'];
$obj = json_decode($obj_post, true);
$total = count($obj);
```
Não há verificação suficiente se `$_POST['acervo']` está definido e se é um JSON válido. Isso pode gerar erros ou comportamento inesperado no código caso o valor não seja o esperado. Recomenda-se verificar se `$_POST['acervo']` está definido e se é um JSON válido antes de tentar decodificá-lo.

4. Na linha:
```php
$registro_select_id_funcionario = mysqli_fetch_row($resultado_select_id_funcionario);
$id_funcionario = $registro_select_id_funcionario[0];
```
A mistura de métodos OOP (consulta preparada) com métodos procedurais (`mysqli_fetch_row`) pode levar a problemas de legibilidade e manutenção do código. Recomenda-se escolher um único estilo de programação (OOP ou procedural) para garantir consistência no código.

Esteja ciente dessas vulnerabilidades e sugira as correções necessárias para melhorar a segurança e a qualidade do código.

**Comment by FlameOff** [comment]
Vulnerabilidade já resolvida
