### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/alergia_upload.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#247]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Falta de verificação de dados de entrada: O código utiliza a função extract($_REQUEST) para extrair os dados da requisição, o que pode resultar em vulnerabilidades de segurança, como ataques de injeção de SQL. Em vez disso, é recomendado usar métodos mais seguros para obter os dados da requisição, como $_POST['nome_variavel'].

2. Falta de sanitização de dados de entrada: Os valores inseridos diretamente no comando SQL sem serem devidamente sanitizados podem resultar em ataques de injeção de SQL. Recomenda-se usar prepared statements com bindValue para fazer a inserção de dados de forma segura no banco de dados.

3. Utilização do tipo de dado incorreto: No trecho do código em que é definida a data de diagnóstico como "0001-01-01", pode ser problemático depender de tal valor para representar um valor padrão ou nulo. É mais seguro utilizar NULL para representar um valor nulo no banco de dados em vez de valores arbitrários.

Sugestões de melhorias:
1. Substitua o uso de extract($_REQUEST) por acesso direto aos dados da requisição ($_POST, $_GET, etc.) e faça a devida validação e sanitização dos dados antes de utilizá-los no código.

2. Utilize prepared statements com bindValue para executar consultas SQL com segurança e impedir ataques de injeção de SQL.

3. Considere usar NULL em vez de valores arbitrários para representar valores nulos no banco de dados.

4. Adicione mensagens de erro mais detalhadas para fornecer feedback adequado ao usuário em caso de falha na execução da consulta SQL.

Essas melhorias ajudarão a tornar o código mais seguro contra ataques e mais resistente a erros.

**Comment by FlameOff** [comment]
Alterações feitas
