### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/adicionar_exame.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#249]
Vulnerability Analysis
1. Falta de tratamento das entradas do usuário: 
   - A vulnerabilidade presente nesse código é a falta de tratamento das entradas do usuário antes de serem utilizadas na consulta SQL. Essa falta de tratamento pode permitir a execução de SQL Injection, uma técnica utilizada por invasores para manipular o banco de dados através da inserção de comandos SQL maliciosos.

Para corrigir essa vulnerabilidade, é recomendável utilizar prepared statements ou funções de escape de parâmetros fornecidas pelo PDO para garantir que as entradas do usuário sejam tratadas de forma segura antes de serem utilizadas em consultas SQL. Exemplo de como isso poderia ser feito:

```php
$situacao = $_POST["situacao"];
$stmt = $pdo->prepare("INSERT INTO saude_exame_tipos(descricao) VALUES(:descricao)");
$stmt->bindParam(':descricao', $situacao);
$stmt->execute();
```

Com essa abordagem, as entradas do usuário são tratadas de forma segura, prevenindo assim a possibilidade de SQL Injection.

Além disso, é importante validar e sanitizar as entradas do usuário antes de utilizá-las em consultas SQL para garantir a integridade e segurança dos dados do sistema.

**Comment by FlameOff** [comment]
O código já foi atualizado com as **correções recomendadas**
