### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/saude/adicionar_alergia.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#251]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. **Injeção de SQL**: O código possui uma vulnerabilidade de injeção de SQL na linha 4, onde o valor da variável `$s2` é diretamente concatenado na query SQL sem qualquer tipo de sanitização ou validação. Isso pode permitir que um atacante injete código malicioso na aplicação.

Recomendações:
1. Para corrigir a vulnerabilidade de injeção de SQL, é altamente recomendado utilizar prepared statements para inserir os valores na query SQL. Dessa forma, os valores serão automaticamente escapados, prevenindo ataques de injeção de SQL. Abaixo está um exemplo de como realizar isso:

```php
$stmt = $pdo->prepare("INSERT INTO saude_tabelacid (CID, descricao) VALUES (?, ?)");
$stmt->bind_param("ss", $alergia_CID, $s2);
$stmt->execute();
```

Certifique-se de validar e sanitizar os dados de entrada antes de utilizá-los em consultas SQL para evitar possíveis vulnerabilidades.

**Comment by GabrielPintoSouza** [comment]
Essa vulnerabilidade já foi corrigida no começo dessa semana, sugiro atualizar com um pull a branch que está sendo utilizada para fazer a análise de vulnerabilidades do sistema.

**Comment by nilsonLazarin** [comment]
@mustafaneto
Vulnerabilidade relatada em: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-wp4f-qhh2-8vfv
Correção em: https://github.com/LabRedesCefetRJ/WeGIA/commit/f35910cb8b9205a6f038ef1e8b3413ea8eee850b
Código da vulnerabilidade:
