### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/pet/informacao_medicamento.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#260]
Vulnerability Analysis
Existem diversas vulnerabilidades no código fornecido:

1. **Injeção de SQL:**
As consultas SQL estão sendo construídas sem o uso de prepared statements, o que torna o código vulnerável a ataques de Injeção de SQL. Por exemplo, na consulta `SELECT * FROM funcionario WHERE id_pessoa=$id_pessoa`, a variável `$id_pessoa` é concatenada diretamente na string SQL sem ser sanitizada.

2. **Cross-Site Scripting (XSS):**
Há um possível problema de XSS na linha:
```php
echo WWW;
```
Caso a variável `WWW` seja definida a partir de uma entrada do usuário ou de uma fonte não confiável, ela poderia conter um script malicioso que seria executado no lado do cliente.

3. **Configuração de erro PHP:**
A função `ini_set('display_startup_errors', 1);` parece conter um erro de digitação (deveria ser `ini_set('display_startup_errors', 1);`). Além disso, a parametrização do `error_reporting` para exibir todos os erros (E_ALL) pode não ser aconselhável em ambientes de produção devido a possíveis problemas de segurança.

4. **Uso de `extract()` sem validação:**
O uso da função `extract($_REQUEST);` pode causar problemas de segurança, pois é possível que variáveis inesperadas sejam extraídas e sobrescrevam variáveis existentes.

5. **Aviso sobre uso de funções obsoletas:**
O uso intercalado de funções `mysqli` e a classe `PDO` para realizar consultas ao banco de dados pode levar a inconsistências no código e aumento da complexidade.

6. **Verificação de Resultados Ineficiente:**
A verificação de resultados de consultas usando `is_null` e `is_bool` não é a maneira mais eficiente de lidar com os resultados de uma consulta, uma vez que pode causar comportamentos inesperados.

7. **Loop Infinito no carregamento do arquivo de configuração:**
Existe um loop infinito na parte em que o script tenta encontrar o arquivo de configuração (`config.php`) relativo ao diretório atual, e caso não exista no diretório atual, ele tenta encontrar no diretório superior. Isso pode causar problemas de desempenho e segurança se um atacante explorar esse loop.

8. **Uso de `extract()` geral:**
O uso indiscriminado da função `extract($_REQUEST);` para extrair todas as informações dos dados recebidos pode criar variáveis globais inseguras e sobrescrever variáveis existentes.

9. **Uso de `required` em `
` `nomeMedicamento` tem o atributo `required`, mas não possui uma opção de fallback ou mensagem de erro personalizada associada, o que pode causar uma experiência frustrante para o usuário.

Recomenda-se corrigir essas vulnerabilidades para garantir a segurança e a robustez do código.

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
05/09/2024

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
05/09/2024
