### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/pet/cadastro_ficha_medica_pet.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#265]
Vulnerability Analysis
1. Falta de validação de dados: O código não faz a validação dos dados recebidos do usuário, o que pode levar a vulnerabilidades de segurança, como ataques de injeção SQL. Recomenda-se sempre validar e sanitizar os dados de entrada antes de utilizá-los em consultas de banco de dados.

2. Uso de `extract($_REQUEST)`: O uso da função `extract()` com `$_REQUEST` pode levar a potenciais vulnerabilidades de segurança, uma vez que ela cria variáveis baseadas nos dados fornecidos pelos usuários. Isso pode ser explorado para acessar variáveis inesperadas ou até mesmo sobrescrever variáveis existentes.

3. Falta de verificação de permissão: O código verifica a permissão do usuário apenas uma vez no início, e se o usuário não tiver permissão adequada, ele é redirecionado para outra página. No entanto, seria mais seguro verificar as permissões em cada operação específica para garantir que o usuário tenha permissão para executar a ação solicitada.

4. Uso de mysqli e PDO juntos: O código mistura o uso da extensão mysqli e da classe PDO para interagir com o banco de dados. Isso pode tornar o código confuso e introduzir potenciais problemas de segurança, além de dificultar a manutenção.

5. Não há uso de prepared statements: As consultas SQL no código não utilizam prepared statements, o que torna o código vulnerável a ataques de injeção SQL. Recomenda-se o uso de prepared statements para proteger contra esse tipo de vulnerabilidade.

Recomendação geral: É importante revisar e ajustar o código para garantir a segurança e robustez da aplicação, seguindo as boas práticas de programação e segurança, como validação de dados, uso correto de consultas SQL e verificação de permissões.

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
12/09/2024
