### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/pet/cadastrar_medicamento.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#266]
Vulnerability Analysis
1. **Variáveis não definidas:**
- As variáveis `$config_path`, `$id_pessoa`, `$id_cargo`, `$resultado`, `$permissao`, `$nome`, `$idsPets`, `$idsPetsFichaMedica`, `$idPet`, `$idPetsCadastrados`, `$idsVerificados` e `$nomesCertos` são usadas sem serem definidas no início do código. Isso pode gerar um aviso ou erro de variável indefinida, a depender da configuração do PHP.

2. **Uso de `extract` para obter variáveis da requisição:**
- O uso da função `extract($_REQUEST);` pode tornar o código vulnerável a ataques de Injeção PHP, pois é possível que variáveis indesejadas sejam criadas no escopo global.

3. **Uso de `mysqli_query` sem prepared statements:**
- O código executa consultas SQL diretamente com o uso da função `mysqli_query`, sem utilizar prepared statements para evitar ataques de injeção de SQL. Recomenda-se o uso de prepared statements para proteger contra esse tipo de vulnerabilidade.

4. **Redirecionamento sem validação de URL:**
- A função `header("Location: ...")` é utilizada para redirecionamento sem validar a URL fornecida, o que pode ser explorado para ataques de Redirecionamento de Página Aberta (Open Redirect).

5. **Divulgação de informações sensíveis:**
- O código contém mensagens que revelam informações sensíveis sobre as permissões do usuário (por exemplo, "Você não tem as permissões necessárias para essa página."). Isso pode ser uma vulnerabilidade de divulgação de informações.

6. **Linha de código não necessária:**
- A linha `require_once "../html/personalizacao_display.php";` não parece estar sendo utilizada no código e pode ser removida.

Para corrigir essas vulnerabilidades, é importante definir as variáveis antes de usá-las, evitar o uso de `extract`, utilizar prepared statements para consultas SQL, validar e sanitizar URLs de redirecionamento, remover mensagens sensíveis e revisar o código para remover partes não utilizadas.

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
12/09/2024
