### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/pessoa/editar_endereco.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#268]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Injeção de SQL: O código está vulnerável a ataques de injeção de SQL devido à forma como os dados são inseridos diretamente na string de consulta SQL. Isso pode permitir que um usuário mal-intencionado execute comandos SQL arbitrários no banco de dados.

Para corrigir a vulnerabilidade de injeção de SQL, recomenda-se o uso de declarações preparadas (prepared statements) ao executar consultas SQL. As declarações preparadas parametrizam as consultas SQL, permitindo que os dados sejam separados dos comandos SQL, o que ajuda a prevenir ataques de injeção de SQL.

Segue um exemplo de como corrigir a vulnerabilidade utilizando declarações preparadas:

```php
$stmt = $pdo->prepare("UPDATE pessoa SET cep=:cep, estado=:uf, cidade=:cidade, bairro=:bairro, logradouro=:rua, complemento=:complemento, ibge=:ibge, numero_endereco=:numero_residencia WHERE id_pessoa=:id_pessoa");

$stmt->bindParam(':cep', $cep);
$stmt->bindParam(':uf', $uf);
$stmt->bindParam(':cidade', $cidade);
$stmt->bindParam(':bairro', $bairro);
$stmt->bindParam(':rua', $rua);
$stmt->bindParam(':complemento', $complemento);
$stmt->bindParam(':ibge', $ibge);
$stmt->bindParam(':numero_residencia', $numero_residencia);
$stmt->bindParam(':id_pessoa', $id_pessoa);

$stmt->execute();
```

Com o uso de declarações preparadas, os valores são passados como parâmetros separados da consulta SQL, evitando assim a vulnerabilidade de injeção de SQL.

Além disso, é importante validar e sanitizar os dados de entrada antes de inseri-los em consultas SQL para evitar outras vulnerabilidades.

**Comment by nicolly015** [comment]
- O comentário foi útil? 4 = Útil 

- O erro foi fácil de localizar? 5 = Muito fácil 

- Foi possível corrigir o erro? Possível 

- O quão fácil de corrigir? 5 = Muito fácil
