### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/pessoa/editar_documentacao.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#269]
Vulnerability Analysis
1. SQL Injection: O código está vulnerável a ataques de injeção de SQL devido ao uso direto das variáveis passadas pelo usuário ($_POST) na construção da query SQL. Isso pode permitir que um atacante execute comandos maliciosos no banco de dados. Recomenda-se o uso de prepared statements para evitar essa vulnerabilidade.

2. XSS (Cross-Site Scripting): O código está vulnerável a ataques de XSS devido ao retorno da variável $_GET na resposta JSON. Se a variável $_GET['sql'] contiver scripts maliciosos, eles serão executados no navegador do usuário. É importante sanitizar e/ou escapar os dados antes de exibi-los no front-end para evitar esse tipo de ataque.

3. Exposição de Informações Sensíveis: A exibição da query SQL no retorno da requisição pode expor informações sensíveis do banco de dados, como a estrutura da tabela e os dados armazenados. Isso pode facilitar potenciais ataques por parte de hackers. Recomenda-se não retornar informações sensíveis desse tipo nas respostas da aplicação.

Para corrigir essas vulnerabilidades, é recomendável:
- Utilizar prepared statements para executar consultas SQL com segurança.
- Sanitizar e/ou escapar os dados antes de exibi-los no front-end para prevenir XSS.
- Evitar retornar informações sensíveis, como queries SQL, nas respostas da aplicação, especialmente para usuários não autenticados.

**Comment by nicolly015** [comment]
- O comentário foi útil? 4 = Útil 

- O erro foi fácil de localizar? 5 = Muito fácil 

- Foi possível corrigir o erro? Possível 

- O quão fácil de corrigir? 4 = Fácil
