### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/funcionario/documento_download.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#299]
Vulnerability Analysis
Potencial vulnerabilidade:   

1. **Injeção de código SQL**  
O código não está escapando ou validando a variável `$_GET["id_doc"]`, o que torna a aplicação vulnerável a ataques de injeção de SQL. Um atacante poderia manipular o valor de `id_doc` na URL para executar comandos SQL maliciosos no banco de dados.

Recomenda-se a utilização de prepared statements para evitar essa vulnerabilidade. Além disso, é aconselhável realizar a validação e sanitização dos dados recebidos através de variáveis superglobais, como `$_GET`.

Para corrigir essa vulnerabilidade, você pode modificar o código da seguinte forma:

```php
$id_doc = filter_var($_GET["id_doc"], FILTER_VALIDATE_INT);

if ($id_doc !== false && $id_doc > 0) {
    $arquivo = new DocumentoFuncionario($id_doc);
    // Restante do código...
} else {
    echo "ID de documento inválido.";
}
```

Além disso, é importante garantir que somente usuários autorizados possam baixar os documentos, verificando as permissões do usuário de forma adequada. Considerando que o script verifica as permissões do usuário através da função `permissao($_SESSION['id_pessoa'], 11, 7)`, é fundamental garantir que apenas usuários com permissões adequadas possam acessar e baixar os documentos.

Certifique-se de validar todas as entradas de dados, limitando as ações permitidas e evitando assim vulnerabilidades.

**Comment by nicolly015** [comment]
- O comentário foi útil?   3 = Neutro 

- O erro foi fácil de localizar?   4 = Fácil 

- Foi possível corrigir o erro?   Possível 

- O quão fácil de corrigir?   3 = Neutro
