### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/funcionario/dependente_parentesco_adicionar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#304]
Vulnerability Analysis
Vulnerabilidades encontradas no código:

1. SQL Injection:
O código está vulnerável a ataques de SQL Injection. A variável `$descricao` é usada diretamente na consulta SQL sem nenhum tipo de tratamento para caracteres especiais. Um atacante pode aproveitar isso para manipular a consulta SQL e realizar operações indevidas no banco de dados.

2. Falta de tratamento de exceções:
Dentro do bloco try-catch, a exceção é capturada mas não está sendo tratada de forma adequada. O código simplesmente recupera a mensagem da exceção com `$e->getMessage()`, mas não faz nada com essa informação. Seria aconselhável adicionar alguma ação para lidar com a exceção, como exibir uma mensagem de erro amigável ao usuário ou registrar o incidente de alguma forma.

3. Injeção de ID de Pessoa:
A função `permissao($_SESSION['id_pessoa'], 11, 7);` parece receber o ID da pessoa logada e utilizá-lo para o controle de permissões. Se essa função não proteger adequadamente esse valor contra injeção de dados, pode haver uma vulnerabilidade de injeção de ID de pessoa.

Recomendações:
- Utilizar prepared statements ou stored procedures para evitar ataques de SQL Injection.
- Tratar de forma adequada as exceções, incluindo ações adequadas de recuperação ou registro de erros.
- Certificar-se de que a função `permissao` protege adequadamente os IDs contra injeção de dados e outros tipos de ataques.

**Comment by nicolly015** [comment]
- O comentário foi útil?   4 = Útil 

- O erro foi fácil de localizar?   5 = Muito fácil 

- Foi possível corrigir o erro?   Possível 

- O quão fácil de corrigir?   5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@nicolly015  o erro persistiu...

@mustafaneto, para seu TCC
Vulnerabilidade relatada pela equipe de segurança: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-xm3h-x3rv-whr5
Código da vulnerabilidade: 
Correção: https://github.com/LabRedesCefetRJ/WeGIA/commit/1825e235aa4ab1b8b641a02c3ec8bc32ea7a8433
