### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/funcionario/dependente_cadastrar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#312]
Vulnerability Analysis
1. Injeção de SQL:  
A vulnerabilidade presente no código é a Injeção de SQL, onde o valor inserido na variável `$cpf` é concatenado diretamente na query SQL da seguinte forma:  
```
$id_pessoa = $pdo->query("SELECT id_pessoa FROM pessoa WHERE cpf = '$cpf';")->fetch(PDO::FETCH_ASSOC)["id_pessoa"];
```
Isso pode permitir que um atacante manipule a entrada do CPF para realizar uma Injeção de SQL, podendo comprometer a segurança do banco de dados. Para mitigar esse tipo de vulnerabilidade, recomenda-se utilizar Prepared Statements com parâmetros vinculados, assim como feito no trecho de código anterior.

2. Mensagens de Erro Expostas:  
Além disso, as mensagens de erro do banco de dados estão sendo exibidas diretamente na tela usando o `echo`, o que pode expor informações sensíveis sobre a estrutura do banco de dados e outras vulnerabilidades. É importante tratar essas mensagens de erro de forma adequada, sem expô-las diretamente aos usuários.

Para corrigir a vulnerabilidade de Injeção de SQL, você pode modificar o trecho de código para usar Prepared Statements corretamente com os parâmetros vinculados, da seguinte forma:

```php
try {
    $stmt = $pdo->prepare("SELECT id_pessoa FROM pessoa WHERE cpf = :cpf");
    $stmt->bindValue(':cpf', $cpf);
    $stmt->execute();
    $result = $stmt->fetch(PDO::FETCH_ASSOC);
    $id_pessoa = $result['id_pessoa'];
} catch (PDOException $th) {
    echo "Houve um erro ao obter o id da pessoa do banco de dados: " . $th->getMessage();
    die();
}
```

Além disso, é importante considerar outras boas práticas de segurança, como validar e filtrar todas as entradas do usuário para evitar possíveis ataques.

**Comment by GabrielPintoSouza** [comment]
Injeção de SQL resolvida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/a22ecbb197260389cf3c4a174e26b760b64f83d3)
Talvez seja melhor considerarmos a criação de uma classe para Dependente, juntamente com a criação do seu controller e DAO.
Também podemos considerar a refatoração do arquivo classes/util.php, de forma que ele tenha as funções necessárias para validar CPF, telefone, RG, datas e etc.
