### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_remover.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#356]
Vulnerability Analysis
1. Vulnerabilidade de Injeção de SQL:
O código está vulnerável a ataques de injeção de SQL na linha que faz a deleção de registros na tabela "atendido_familiares":
```php
$pdo->query("DELETE FROM atendido_familiares WHERE idatendido_familiares = $id_dependente;");
```
Para corrigir essa vulnerabilidade, é recomendado utilizar prepared statements para realizar consultas SQL parametrizadas. Dessa forma, os valores dos parâmetros não são interpretados como comandos SQL maliciosos.

2. Vulnerabilidade de Acesso Direto a Arquivos:
O código faz uma verificação de permissão de usuário e redireciona para o `../../index.php` caso o usuário não esteja logado. No entanto, não há uma verificação adicional de permissão antes de executar a ação de deleção de dependente. Isso pode permitir que um usuário autenticado, mas sem permissão, acesse e execute a ação de deleção.

Sugestões para correção:
- Adicionar uma verificação de permissão antes de executar a ação de deleção de dependentes para garantir que apenas usuários com permissão adequada possam realizar essa operação.
- Utilizar prepared statements para proteger contra injeção de SQL.
- Reforçar as verificações de permissão no código.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade resolvida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/0c2c59d9436632e8d1590f6594fb93bb869202b9).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
