### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_parentesco_adicionar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#358]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Injeção de SQL: O código está vulnerável a ataques de injeção de SQL devido ao uso direto da variável `$descricao` na construção da consulta SQL sem nenhum tipo de sanitização. Isso pode permitir que um usuário mal-intencionado execute comandos SQL maliciosos no banco de dados.

Recomendação:
Para corrigir a vulnerabilidade de injeção de SQL, recomenda-se utilizar declarações preparadas (prepared statements) em vez de interpolar diretamente variáveis no SQL. Abaixo está um exemplo de como o código poderia ser corrigido:
```php
$descricao = $_POST["parentesco"];
$stmt = $pdo->prepare("INSERT INTO atendido_parentesco (parentesco) VALUES (:descricao)");
$stmt->bindParam(':descricao', $descricao);
$stmt->execute();
```

Além disso, considere realizar validações nos dados recebidos do usuário para garantir que estejam no formato esperado antes de inseri-los no banco de dados.

**Comment by GabrielPintoSouza** [comment]
O arquivo familiar_parentesco_adicionar.php não está sendo chamado em nenhum lugar do sistema, avaliar possível remoção.
