### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_listar_um.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#360]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. **Vulnerabilidade de SQL Injection:** A vulnerabilidade é causada pela concatenação direta de dados fornecidos pelo usuário ($_POST["id_dependente"]) na query SQL sem nenhum tipo de validação ou escape dos dados. Isso abre a porta para ataques de injeção de SQL. Um invasor pode manipular o valor de "id_dependente" para executar comandos maliciosos no banco de dados.

Solução:
Para corrigir essa vulnerabilidade, você deve utilizar prepared statements para executar consultas SQL parametrizadas com valores seguros. Isso ajuda a prevenir a injeção de SQL. Aqui está um exemplo de como você pode modificar o código para evitar a vulnerabilidade de SQL Injection:

```php
$id_dependente = $_POST["id_dependente"];

// Preparar a consulta SQL com um parâmetro
$stmt = $pdo->prepare("SELECT *, ap.parentesco AS parentesco
FROM atendido_familiares af
LEFT JOIN pessoa p ON p.id_pessoa = af.pessoa_id_pessoa
LEFT JOIN atendido_parentesco ap ON ap.idatendido_parentesco = af.atendido_parentesco_idatendido_parentesco
WHERE af.idatendido_familiares= :id_dependente");

// Vincular o valor do parâmetro e executar a consulta
$stmt->bindParam(':id_dependente', $id_dependente);
$stmt->execute();

$dependente = $stmt->fetch(PDO::FETCH_ASSOC);

$dependente = json_encode($dependente);
```

Além disso, é importante validar e filtrar os dados do usuário antes de passá-los para consultas SQL. Dessa forma, você garante a segurança do seu aplicativo contra ataques de injeção de SQL.

2. **Falta de tratamento de erros:** O código não possui um tratamento de erros adequado para lidar com falhas na execução da query SQL. É importante verificar se a consulta foi executada com sucesso e lidar com possíveis erros para garantir o bom funcionamento do aplicativo e uma melhor experiência do usuário.

**Dica de boas práticas:**
- Sempre valide e filtre os dados fornecidos pelo usuário antes de utilizá-los em consultas SQL para evitar vulnerabilidades de segurança.
- Utilize prepared statements para consultas SQL parametrizadas, em vez de concatenar diretamente os valores na query.
- Implemente um tratamento de erros adequado para lidar com possíveis falhas na execução de consultas SQL e outros processos críticos.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/68d12330e25df12682a4bdf1795c0ba6ce69aa3a).
