### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_editarInfoPessoal.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#361]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. O código está vulnerável a Injeção de SQL: O código utiliza o método `prepare` para preparar a query, o que ajuda a prevenir ataques de Injeção de SQL. No entanto, os valores das variáveis `$id`, `$nome`, `$sobrenome`, `$sexo`, `$telefone`, `$data_nascimento`, `$nome_mae` e `$nome_pai` estão sendo diretamente utilizados na query sem serem previamente sanitizados. Recomenda-se utilizar funções como `filter_var` ou `htmlspecialchars` para filtrar e sanitizar os valores inseridos no banco de dados.

2. Não há validação de dados de entrada: O código não faz nenhuma validação dos dados recebidos via `$_POST` e `$_GET`, como verificar se os campos obrigatórios estão preenchidos, se os tipos de dados são válidos, entre outros. Isso pode levar a erros ou vulnerabilidades no sistema.

3. Erro de sintaxe na cláusula WHERE na query SQL: Na query de atualização, a cláusula WHERE está escrita como "where id_pessoa = :id", o correto seria "WHERE id_pessoa = :id".

4. Uso de extract() é inseguro: A função `extract` utiliza as chaves do array associativo para criar variáveis no escopo atual, o que pode causar conflitos de nome e tornar o código menos legível e mais propenso a erros. É uma prática considerada insegura e não é recomendada.

Considerações finais:
Para corrigir as vulnerabilidades e melhorar a segurança do código, é importante aplicar as seguintes medidas:
- Sanitizar e validar os dados recebidos do usuário antes de utilizá-los em consultas SQL.
- Utilizar declaração preparada e vinculação de parâmetros em todas as consultas SQL para evitar Injeção de SQL.
- Corrigir possíveis erros de sintaxe na query SQL, como o caso mencionado do WHERE.
- Evitar o uso da função extract().
- Implementar validações de dados de entrada para garantir a integridade dos dados.
- Tratar devidamente eventuais exceções lançadas pela execução das consultas SQL.

Essas recomendações ajudarão a fortalecer a segurança e a robustez do código.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/5f780311a369a969cb56939979d5a0e38f2a6b78).
