### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_editarEndereco.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#362]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Injeção de SQL: O código utiliza a função extract($_REQUEST) para extrair variáveis de um array, que pode facilitar ataques de injeção de SQL se o array $_REQUEST for manipulado por um usuário mal-intencionado. Recomenda-se evitar o uso da função extract e acessar as variáveis diretamente do array $_REQUEST.

2. Falta de validação de entrada: Não há validação adequada dos dados recebidos através do método POST. Isso pode resultar em erros ou problemas de segurança se os dados não forem do tipo esperado.

3. Injeção de código: O código não filtra ou valida as variáveis recebidas através do método GET, o que pode resultar em vulnerabilidades de injeção de código.

4. Exposição de informações sensíveis: O código está exibindo mensagens de erro do PDO diretamente na tela em caso de exceção, o que pode expor informações sensíveis sobre a estrutura do banco de dados. É recomendável tratar as exceções de forma mais genérica e não exibir mensagens de erro diretamente aos usuários.

5. Redirecionamento inseguro: O código realiza um redirecionamento de página utilizando a variável $idatendido_familiares, que é obtida diretamente do GET. Isso pode ser vulnerável a ataques de redirecionamento não seguro, conhecido como Open Redirect, onde um invasor pode manipular a variável para redirecionar os usuários para um site malicioso.

Sugestões de correção:
1. Evite o uso da função extract e prefira acessar as variáveis diretamente do array $_REQUEST.
2. Valide e sanitize os dados recebidos do método POST antes de utilizá-los em consultas SQL.
3. Filtrar e validar os dados recebidos através do método GET para prevenir injeção de código.
4. Utilize blocos try-catch para tratar exceções PDO de forma mais genérica e não exiba mensagens de erro diretamente aos usuários.
5. Verifique e sanitize os dados antes de redirecionar a página para evitar vulnerabilidades de redirecionamento não seguro.

**Comment by nicolly015** [comment]
- O comentário foi útil?   3 = Neutro 

- O erro foi fácil de localizar?   5 = Muito fácil 

- Foi possível corrigir o erro?   Possível

- O quão fácil de corrigir?   5 = Muito fácil
