### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_editarDoc.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#363]
Vulnerability Analysis
1. O código está vulnerável a ataques de injeção de SQL, pois utiliza diretamente os valores de $_POST e $_GET na query SQL sem validação ou sanitização adequadas. Recomenda-se utilizar declarações preparadas com bindParam ou bindValue para proteger contra esse tipo de ataque.

2. O código não verifica se os parâmetros $_GET['id_pessoa'] e $_GET['idatendido_familiares'] são definidos antes de usá-los. Isso pode resultar em um erro "Undefined index" se os parâmetros não estiverem presentes na URL.

3. A condição `if(count($data_expedicao) <10)` está incorreta, pois $data_expedicao é uma string e não um array. Ela deveria ser verificada se é nula ou vazia, e não contar o número de caracteres.

4. A mensagem de erro exibida no catch pode revelar informações sensíveis sobre a estrutura do banco de dados, o que não é recomendado em ambientes de produção. Melhor seria informar uma mensagem genérica ao usuário.

5. A função `extract($_REQUEST)` é perigosa, pois pode causar a sobrescrita de variáveis existentes e abrir espaço para vulnerabilidades. É recomendável evitar seu uso e acessar as variáveis diretamente de $_POST ou $_GET.

Para corrigir as vulnerabilidades, é sugerido:
- Utilizar declarações preparadas com bindParam ou bindValue para proteger contra SQL Injection.
- Verificar se os parâmetros $_GET['id_pessoa'] e $_GET['idatendido_familiares'] existem antes de acessá-los.
- Corrigir a condição de verificação de $data_expedicao.
- Evitar exibir mensagens de erro detalhadas para usuários finais.
- Evitar o uso da função extract($_REQUEST) e acessar variáveis diretamente de $_POST ou $_GET.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/55937172c231a310f63e27d4b9a0a432a820ab10).
