### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_documento.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#364]
Vulnerability Analysis
1. Vulnerabilidade de Injeção de SQL: O código está vulnerável a ataques de injeção de SQL devido à concatenação direta de variáveis na query SQL. Um usuário mal-intencionado pode enviar um valor manipulado para `$id_dependente` e executar comandos SQL maliciosos. Recomenda-se utilizar prepared statements para proteger contra esse tipo de vulnerabilidade.

2. Revelação de Informações Sensíveis: O código retorna informações confidenciais mantendo o conteúdo do banco de dados em formato JSON. Dependendo dos dados retornados, informações sensíveis podem ser expostas a usuários não autorizados. Recomenda-se não retornar diretamente os resultados do banco de dados para os usuários e proteger adequadamente as informações sensíveis.

Para corrigir essas vulnerabilidades, sugiro o seguinte ajuste no código:

```php
$id_dependente = $_POST["id_dependente"];
$stmt = $pdo->prepare("SELECT doc.nome_docdependente AS descricao, ddoc.data, ddoc.id_doc FROM funcionario_dependentes_docs ddoc LEFT JOIN funcionario_docdependentes doc ON doc.id_docdependentes = ddoc.id_docdependentes WHERE ddoc.id_dependente=:id_dependente");
$stmt->bindParam(':id_dependente', $id_dependente, PDO::PARAM_INT);
$stmt->execute();
$dependente = $stmt->fetchAll(PDO::FETCH_ASSOC);

// A partir daqui, você pode tratar os dados de forma segura e adequada antes de retorná-los.

echo json_encode($dependente);
```

Certifique-se de validar e filtrar corretamente os dados de entrada antes de usá-los em consultas SQL e proteger as informações sensíveis retornadas ao cliente de forma adequada.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/246f29d5f07a87aa95afd88d8e6d4cb87f916a22).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
