### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/familiar_cadastrar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#366]
Vulnerability Analysis
1. A função `extract($_REQUEST)` pode ser perigosa, pois extrai variáveis ​​do array $_REQUEST para o escopo global. Isso pode levar a possíveis vulnerabilidades de segurança, como a sobrescrita de variáveis ​​existentes ou a introdução de variáveis ​​não desejadas no escopo global. É recomendado evitar o uso da função `extract()` e acessar diretamente as variáveis ​​do array $_REQUEST.

2. A consulta SQL usada para obter o ID da pessoa com base no CPF não está usando prepared statements, o que pode deixar o sistema vulnerável a ataques de injeção de SQL. Recomenda-se usar prepared statements para garantir a segurança e evitar vulnerabilidades de segurança.

3. A consulta SQL para inserir um novo familiar não está usando prepared statements e está concatenando diretamente as variáveis no SQL, o que pode resultar em vulnerabilidades de injeção de SQL. É importante modificar essa parte do código para utilizar prepared statements e evitar esse tipo de vulnerabilidade.

4. A mensagem de erro exibida diretamente na página pode fornecer informações sensíveis sobre a estrutura do banco de dados ou outras informações que possam auxiliar um potencial invasor. Recomenda-se tratar as mensagens de erro de forma mais genérica e não exibi-las diretamente para os usuários finais.

Para corrigir essas vulnerabilidades, sugiro realizar as seguintes alterações:
- Remover o uso da função `extract($_REQUEST)` e acessar diretamente as variáveis ​​do array $_REQUEST.
- Utilizar prepared statements para todas as consultas SQL, garantindo a segurança e evitando injeção de SQL.
- Tratar as mensagens de erro de forma genérica e não exibi-las diretamente na página. Em vez disso, registrar os erros de forma segura para revisão posterior.

Essas correções ajudarão a fortalecer a segurança do código e a proteger contra possíveis vulnerabilidades.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidades corrigidas no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/fc7d2c3ce28430ed1f5c719f08c183c3b859cc91)

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
