### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/exibe_anexo.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#367]
Vulnerability Analysis
1. A vulnerabilidade neste código está na linha:

```php
$id_anexo = $_GET['idatendido_ocorrencias'];
$extensao = $_GET['extensao'];
$nome = $_GET['nome'];
```

Estas linhas estão pegando os valores diretamente da superglobal `$_GET`, o que torna vulnerável o código a ataques de Injeção de código, especialmente Injeção de SQL. Um atacante mal-intencionado pode manipular esses dados passados pela URL para executar comandos maliciosos no sistema.

Para corrigir esta vulnerabilidade, é importante sempre validar e sanitizar os dados que vêm de fontes não confiáveis, como as superglobais `$_GET`, `$_POST`, `$_REQUEST`, etc.

Além disso, as outras partes do código também podem ser vulneráveis, dependendo do conteúdo do arquivo `config.php` e da forma como ele é incluído no código.

2. Além disso, o uso da função `require_once` para incluir o arquivo de configuração pode ser problemático, pois se um atacante conseguir acessar diretamente o arquivo `config.php`, ele poderá ver os dados sensíveis contidos nele, como credenciais de banco de dados.

É importante garantir que o arquivo de configuração não possa ser acessado diretamente pelo usuário, talvez movendo-o para um diretório que não é acessível via navegador.

3. A função `force-download` usada na linha:

```php
header('Content-Type: application/force-download');
```

Está obsoleta e foi removida das especificações HTTP. Em vez disso, é recomendável usar o tipo de conteúdo `application/octet-stream` para forçar o download de arquivos.

4. A linha:

```php
/*Header('Content-Disposition: attachment; filename="'.$nome.'.'.$extensao);*/
```

Está comentada, o que pode indicar código não utilizado ou um erro de digitação. Certifique-se de revisar e limpar o código de qualquer parte não utilizada para manter a segurança e a clareza do código.

Lembrando sempre a importância de validar e sanitizar os dados vindos de fontes externas antes de utilizá-los no código para prevenir vulnerabilidades de segurança.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/9e333a15622f84bb7219972328b6e0c022b6fefd).
