### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/documento.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#368]
Vulnerability Analysis
1. Vulnerabilidade de SQL Injection:
O código está vulnerável a ataques de SQL Injection na consulta do construtor e no método `delete()`, pois a variável `$id` é concatenada diretamente na query SQL, sem a devida sanitização. Isso pode permitir que um atacante manipule a consulta SQL de forma maliciosa.

2. Exceção não tratada no método delete():
No método `delete()`, após a execução da query de remoção, é feito um fetch em um resultado que não existe. Isso pode gerar um erro e não é necessário realizar essa operação, já que o DELETE não retorna nenhum dado para ser fetch. Além disso, a exceção não é tratada adequadamente.

3. Uso de funções vulneráveis:
É utilizado a função `base64_decode` e `gzuncompress` para descompactar e decodificar o documento. No entanto, ambas as funções não são seguras e podem ser exploradas por atacantes para manipular e executar código malicioso.

Sugestões para correção:
- Utilize prepared statements para prevenir ataques de SQL Injection.
- Remova a operação de fetch após um DELETE na função delete().
- Utilize funções mais seguras para a manipulação do documento, como `file_get_contents()` para obter o conteúdo do arquivo sem decodificações potencialmente perigosas.

Além disso, é recomendável implementar tratamento de exceções mais detalhado e específico para cada tipo de erro que possa ocorrer.

**Comment by nicolly015** [comment]
- O comentário foi útil?   4 = Útil 

- O erro foi fácil de localizar?   5 = Muito fácil 

- Foi possível corrigir o erro?   Possível 

- O quão fácil de corrigir?   3 = Neutro
