### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/documento_excluir.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#370]
Vulnerability Analysis
O código apresenta algumas vulnerabilidades em potencial:

1. Utilização da função extract(): A função extract() é considerada perigosa e insegura, pois extrai variáveis diretamente para o escopo global, o que pode resultar em possíveis conflitos de variáveis e até mesmo em ataques de injeção de código. É recomendável evitar o uso dessa função e acessar as variáveis diretamente por meio do array $_GET ou $_POST.

2. Falta de validação de dados de entrada ($_GET): O código utiliza diretamente dados provenientes da variável $_GET, sem realizar qualquer tipo de validação ou sanitização. Isso pode deixar o sistema vulnerável a ataques de injeção de SQL, como SQL Injection. Recomenda-se sempre validar e sanitizar os dados de entrada antes de utilizá-los em consultas ou operações no banco de dados.

3. Falta de tratamento de erros no acesso ao banco de dados: O código não contém nenhum tratamento de erros ou exceções no acesso ao banco de dados. Caso ocorra algum erro na consulta SQL ou na conexão com o banco, o código não irá tratar essa situação, o que pode resultar em vazamento de informações sensíveis ou falhas de segurança.

Para corrigir essas vulnerabilidades, sugere-se as seguintes melhorias:

1. Remova a função extract() e utilize as variáveis diretamente a partir do array $_GET, evitando assim possíveis problemas de segurança.

2. Valide e sanitize os dados de entrada provenientes da variável $_GET antes de utilizá-los em consultas SQL. Utilize funções como filter_input() para validar os dados e prepare statements para consultas SQL parametrizadas.

3. Adicione tratamento de erros adequado no acesso ao banco de dados, utilizando blocos try-catch para capturar exceções e lidar com possíveis falhas de forma segura e controlada.

Ao implementar essas correções, o código se tornará mais seguro e menos propenso a vulnerabilidades.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/4994b412df82593b93e497f3ffa4fcbe242a4bda).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
