### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/documento_download.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#371]
Vulnerability Analysis
1. A função `extract($_REQUEST);` não é segura e pode causar vulnerabilidades, pois extrai variáveis ​​do array de entrada para o escopo global do script. Isso pode resultar em variáveis ​​involuntariamente sobrescrevendo as variáveis ​​existentes no script, o que pode levar a vulnerabilidades de segurança, como possibilidade de Injeção de código no script. É recomendado evitar o uso desta função e em vez disso, acessar os valores diretamente a partir do array $_REQUEST.

2. O código não tem validação adequada dos dados de entrada. Ao usar `$_GET["id_doc"]` diretamente na instância do objeto `DocumentoAtendido`, o código está confiando cegamente nos dados fornecidos pelo usuário, sem verificar se é um valor válido e seguro. Isso poderia ser explorado por um atacante para realizar ataques de Injeção ou manipulação de dados.

3. A extensão 'docx' está incorretamente definida como 'application/docx', quando na realidade deveria ser 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'. Isso poderia causar problemas de compatibilidade ao tentar abrir o arquivo. Recomenda-se corrigir isso para garantir que a definição de tipo de conteúdo seja precisa.

4. Não há tratamento adequado para erros ou exceções ao buscar o arquivo. O código simplesmente exibe a mensagem de exceção (se houver) para o usuário, o que pode divulgar informações sensíveis sobre a aplicação. É importante capturar e tratar corretamente as exceções, fornecendo mensagens genéricas de erro ao usuário para evitar vazamento de informações confidenciais.

Sugestões de melhoria:
- Remover o uso da função `extract($_REQUEST);` e acessar diretamente os valores da superglobal `$_REQUEST`.
- Validar e sanitizar os dados de entrada, especialmente antes de usá-los em consultas de banco de dados ou em instâncias de objetos.
- Adicionar tratamento para erros e exceções, garantindo que mensagens genéricas sejam exibidas para o usuário em caso de falha.
- Corrigir a definição incorreta da extensão 'docx' para o tipo correto 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'.

Essas melhorias ajudarão a fortalecer a segurança e a confiabilidade do código.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/13f286dd41eaf52e5be22ec95ea1ae69720e4937).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito fácil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
