### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/Cadastro_Atendido.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#374]
Vulnerability Analysis
1. **Vulnerabilidade de SQL Injection**:
   - A variável `$id_pessoa` é diretamente inserida em uma query SQL sem passar por nenhum tipo de sanitização ou validação. Isso deixa o sistema vulnerável a ataques de injeção de SQL, onde um usuário mal-intencionado poderia manipular o valor da variável para inserir comandos SQL maliciosos.

2. **Vulnerabilidade de Redirecionamento Não Autorizado**:
   - No código, as diretivas `header("Location: ...")` são utilizadas para redirecionar o usuário com base em certas condições. No entanto, o controle de acesso não é realizado de maneira apropriada antes de redirecionar o usuário. Isso pode levar a um possível redirecionamento não autorizado, onde um invasor poderia manipular as variáveis de sessão ou parâmetros de URL para acessar páginas não autorizadas.

3. **Possível Loop Infinito**:
   - Existe um trecho de código onde há um `while (true)` sem uma condição de parada explícita. Se o arquivo de configuração não for encontrado e o loop não for interrompido adequadamente, isso pode resultar em um loop infinito, consumindo recursos do servidor.

4. **Dupla Verificação de Sessão**:
   - Há duas verificações de sessão distintas, uma no início e outra após o carregamento inicial dos recursos do site. Isso é redundante e pode causar confusão no controle de acesso e nas permissões do usuário.

5. **Manuseio de Erros não Implementado**:
   - Não há tratamento de erros adequado ao executar consultas SQL ou ao manipular dados recebidos do usuário. Isso pode levar a vulnerabilidades de segurança, exposição de informações sensíveis e comportamento inesperado do sistema.

Para corrigir essas vulnerabilidades, é recomendado adotar práticas seguras de programação, sanitização de dados de entrada, implementação de controle de acesso adequado, tratamento de erros eficaz e evitar funções obsoletas. Além disso, validar todos os dados antes de usá-los em consultas SQL e evitar a concatenação direta de strings em instruções SQL.

**Comment by nicolly015** [comment]
- O comentário foi útil? 4 = Útil 

- O erro foi fácil de localizar? 5 = Muito fácil 

- Foi possível corrigir o erro? Possível 

- O quão fácil de corrigir? 5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@nicolly015 a vulnerabilidade persistiu...

@mustafaneto, para seu TCC
Vulnerabilidade relatada pela equipe de segurança: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-6q73-74pc-p3c8
Código da vulnerabilidade:  
Correção: https://github.com/LabRedesCefetRJ/WeGIA/commit/61ae1c3bec3c76e039f5ef48bc46cea30562192e
