### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/cadastro_atendido_parentesco_adicionar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#377]
Vulnerability Analysis
A vulnerabilidade no código está na forma como a variável "$descricao" é inserida na query de inserção, sem nenhum tipo de sanitização ou escape de caracteres. Isso torna o código vulnerável a ataques de injeção de SQL.

Para corrigir essa vulnerabilidade, é recomendado utilizar prepared statements para inserir os dados de forma segura. Abaixo está o código corrigido:

```php
session_start();
if (!isset($_SESSION["usuario"])) {
    header("Location: ../../index.php");
}

// Verifica Permissão do Usuário
require_once '../permissao/permissao.php';
permissao($_SESSION['id_pessoa'], 11, 7);
require_once '../../dao/Conexao.php';
try {
    $pdo = Conexao::connect();
    $descricao = $_POST["descricao"];

    $stmt = $pdo->prepare("INSERT INTO atendido_parentesco (parentesco) VALUES (:descricao)");
    $stmt->bindParam(':descricao', $descricao);
    $stmt->execute();
} catch (PDOException $e) {
    echo $e->getMessage();
    exit;
}
die();
```

Neste código corrigido, utiliza-se prepared statements e bindParam para inserir o valor de "$descricao" de forma segura na query de inserção, prevenindo assim ataques de injeção de SQL. Além disso, é importante exibir a mensagem de erro da exceção em caso de falha na execução da query.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/5d4083c0dbbe266e563c33234ffc78e18406fce6)

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
