### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/atendido/atendido_parentesco_adicionar.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#383]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Falta de filtro de dados: A variável `$descricao` é utilizada diretamente na query SQL sem nenhum tipo de validação, o que deixa o código vulnerável a ataques de SQL Injection. Um invasor pode inserir comandos maliciosos no campo de descrição e comprometer a segurança do sistema.

2. Falta de tratamento de erro adequado: No bloco catch, a mensagem de erro obtida através de `$e->getMessage()` não está sendo exibida ou tratada de forma adequada, o que dificulta a identificação de problemas e a resolução de possíveis falhas no sistema.

Sugestões de melhorias:
- Utilize prepared statements para inserir dados na base de dados, substituindo a concatenação de strings na query SQL. Isso ajuda a prevenir ataques de SQL Injection. Exemplo:

```php
$stmt = $pdo->prepare("INSERT INTO atendido_parentesco (parentesco) VALUES (:descricao)");
$stmt->bindParam(':descricao', $descricao);
$stmt->execute();
```

- Adicione um tratamento adequado para as exceções lançadas pela execução da query, exibindo mensagens de erro significativas ou registrando o erro em um arquivo de log. Isso ajuda na identificação e resolução de problemas no sistema.

```php
catch (PDOException $e) {
    echo "Erro ao executar a query: " . $e->getMessage();
    // Ou registre o erro em um arquivo de log
}
```

Essas são algumas melhorias que podem ser feitas para tornar o código mais seguro e robusto.

**Comment by nicolly015** [comment]
- O comentário foi útil? 4 = Útil 

- O erro foi fácil de localizar? 5 = Muito fácil 

- Foi possível corrigir o erro? Possível 

- O quão fácil de corrigir? 5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@mustafaneto
Vulnerabilidade relatada em: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-x3wr-75qx-55cw
