### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/SinaisVitaisDAO.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#393]
Vulnerability Analysis
A vulnerabilidade no código é que a conexão com o banco de dados não está sendo fechada adequadamente após a execução da consulta. O método `close()` utilizado no código não existe no objeto `$pdo`. Para fechar a conexão corretamente, deve-se usar o método `null` ou `nullify()` em vez de `close()`.

Além disso, pode haver um problema de segurança caso o arquivo `config.php` não seja encontrado no loop, pois o script irá subir um nível de diretório a cada iteração. Isso pode resultar em tentativas de inclusão de arquivos em locais sensíveis do sistema de arquivos.

Para corrigir as vulnerabilidades no código, sugerimos as seguintes alterações:

1. Substituir `$pdo->close();` por `$pdo = null;` após o `commit()` para fechar a conexão adequadamente.
2. Adicionar um limite para o número de iterações no loop que busca o arquivo `config.php` para evitar acessar diretórios sensíveis do sistema de arquivos.

Segue o código corrigido:

```php
$config_path = "config.php";
$attempts = 0;
$max_attempts = 5; // Defina um limite para o número de tentativas
if(file_exists($config_path)){
    require_once($config_path);
}else{
    while($attempts < $max_attempts){
        $config_path = "../" . $config_path;
        if(file_exists($config_path)) break;
        $attempts++;
    }
    require_once($config_path);
}
require_once ROOT."/dao/Conexao.php";
require_once ROOT."/classes/SinaisVitais.php";
require_once ROOT."/Functions/funcoes.php";

class SinaisVitaisDAO {
    public function incluir($sinaisvitais) {
        try {
            // código de inclusão...
            
            $sql = "INSERT INTO saude_sinais_vitais (id_fichamedica, id_funcionario, data, saturacao, pressao_arterial, frequencia_cardiaca, frequencia_respiratoria, temperatura, hgt) VALUES (:id_fichamedica, :id_funcionario, :data, :saturacao, :pressao_arterial, :frequencia_cardiaca, :frequencia_respiratoria, :temperatura, :hgt)";
            $pdo = Conexao::connect();
            $stmt = $pdo->prepare($sql);
            $stmt->bindParam(':id_fichamedica', $id_fichamedica);
            // restante do código...

            $stmt->execute();
            $pdo->commit();
            $pdo = null; // Fechar a conexão corretamente
        } catch (PDOException $e) {
            echo 'Error:   na tabela pessoas = ' . $sql . ' 

' . $e->getMessage();
        }
    }
}
``` 

Com essas correções, a conexão com o banco de dados será fechada corretamente após a execução da consulta e o problema de inclusão de arquivos sensíveis será mitigado.

**Comment by FlameOff** [comment]
Correção já feita
