### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/AvisoNotificacaoDAO.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#431]
Vulnerability Analysis
Vulnerabilidades encontradas no código:

1. Injeção de SQL no método `buscarRecentes`, `buscarHistoricos`, `contarRecentes` e `alterarStatus`:
   - Nas consultas SQL desses métodos, o valor de `$idPessoa` é concatenado diretamente na string SQL, o que torna o código vulnerável a ataques de injeção de SQL. Para corrigir essa vulnerabilidade, recomenda-se utilizar prepared statements com placeholders para os parâmetros a serem passados na consulta.

2. Falha ao tratar exceções na captura de erros:
   - No bloco `catch` das exceções `PDOException`, o código apenas pega a mensagem de erro através de `$e->getMessage()`, mas não faz nada com essa informação. Isso pode resultar em uma falha de tratamento de erros, pois não está sendo feito nenhum log, tratamento adequado ou retorno de erro para quem chama os métodos.

Para corrigir essas vulnerabilidades, você pode fazer as seguintes alterações:

1. Altere os métodos `buscarRecentes`, `buscarHistoricos`, `contarRecentes` e `alterarStatus` para utilizar prepared statements com placeholders para evitar a injeção de SQL. Exemplo:

```php
$sql = "SELECT a.descricao, a.data, p.nome as atendido_nome, p.sobrenome as atendido_sobrenome, pe.nome as funcionario_nome, pe.sobrenome as funcionario_sobrenome
        FROM pessoa as p 
        JOIN aviso as a ON (p.id_pessoa=a.id_pessoa_atendida) 
        JOIN aviso_notificacao as an ON (a.id_aviso=an.id_aviso) 
        JOIN funcionario as f ON (an.id_funcionario=f.id_funcionario) 
        JOIN funcionario as fu ON (a.id_funcionario_aviso=fu.id_funcionario) 
        JOIN pessoa as pe ON(fu.id_pessoa=pe.id_pessoa) 
        WHERE f.id_pessoa=:idPessoa AND an.status=1
        ORDER BY a.data DESC";
$stmt = $this->pdo->prepare($sql);
$stmt->bindParam(':idPessoa', $idPessoa, PDO::PARAM_INT);
$stmt->execute();
```

2. Adicione tratamentos adequados para as exceções lançadas no bloco `catch` das classes. Pode ser feito lançando uma nova exceção para cima na pilha de chamadas ou registrando o erro em um log, por exemplo:

```php
catch (PDOException $e) {
    throw new Exception('Erro no banco de dados: ' . $e->getMessage());
}
```

Essas são algumas recomendações para corrigir as vulnerabilidades identificadas no código apresentado.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
