### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/AlmoxarifadoDAO.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#437]
Vulnerability Analysis
1. Vulnerabilidade de SQL Injection:
O código está vulnerável a ataques de SQL Injection devido ao uso da concatenação de strings na construção da consulta SQL. A forma correta de evitar esse tipo de vulnerabilidade é utilizando prepared statements, como é feito no método `listarUm`.

2. Erro de digitação na exceção:
Na exceção `catch (PDOExeption $e)`, a classe `PDOExeption` está escrita de forma errada. O correto seria `PDOException`.

3. Variável `$almoxarifado` não definida:
No método `listarUm`, a variável `$almoxarifado` é definida dentro de um `while`, mas é retornada fora do loop. Isso pode causar um erro de variável não definida se a consulta não retornar resultados.

4. Utilização de função inexistente:
Na exceção de `listarTodos`, está sendo chamado a função `getMessage` sem usar os parênteses. O correto seria `$e->getMessage()`.

Para corrigir as vulnerabilidades e erros mencionados:
- Utilize prepared statements em todos os métodos que constroem consultas SQL.
- Corrija a classe da exceção para `PDOException`.
- Verifique a lógica de definição e retorno da variável `$almoxarifado` no método `listarUm`.
- Corrija a chamada da função `getMessage` na exceção de `listarTodos`.

Essas correções garantirão a segurança e integridade do código no que diz respeito a vulnerabilidades e erros comuns.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 4 = Útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
