### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_tipo_docs_atendido.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#438]
Vulnerability Analysis
O código apresenta uma vulnerabilidade de segurança conhecida como SQL Injection. 

A vulnerabilidade ocorre na linha onde o SQL é construído:

```php
$sql = "INSERT into atendido_docs_atendidos(descricao) values('" .$descricao ."')";
```

Neste trecho, a variável `$descricao` é diretamente concatenada à string SQL, sem nenhum tipo de sanitização ou validação. Isso permite que um atacante possa manipular a string de entrada de forma maliciosa e executar comandos SQL indesejados, comprometendo a integridade dos dados no banco de dados.

Para corrigir essa vulnerabilidade, é altamente recomendado utilizar prepared statements, que permitem separar os dados dos comandos SQL, impedindo a execução de código malicioso. Aqui está um exemplo de como o código poderia ser reescrito usando prepared statements:

```php
$sql = "INSERT into atendido_docs_atendidos(descricao) values(:descricao)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':descricao', $descricao, PDO::PARAM_STR);
$stmt->execute();
```

Dessa forma, o valor da variável `$descricao` será tratado como um parâmetro seguro e não permitirá a execução de comandos SQL maliciosos.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/d30db3c23e0d8da4ee5ec57b8547bcf10cc11edf).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
