### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_tipo_atendido.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#439]
Vulnerability Analysis
A vulnerabilidade presente neste código é a chamada de dados diretamente do array `$_POST` sem realizar nenhum tipo de validação ou sanitização dos dados inseridos pelo usuário. Isso pode resultar em uma vulnerabilidade de injeção de SQL, onde um usuário mal-intencionado pode inserir comandos SQL maliciosos no campo de descrição e comprometer a segurança do sistema.

Para corrigir essa vulnerabilidade, é importante utilizar prepared statements com parâmetros. Abaixo está o código corrigido:

```php
prepare($sql);
	$stmt->bindParam(':descricao', $descricao, PDO::PARAM_STR);
	$stmt->execute();
?>
```

Com essa correção, os dados do usuário serão tratados de forma segura, evitando a execução de comandos SQL maliciosos. O uso de prepared statements com parâmetros ajuda a prevenir ataques de injeção de SQL, tornando o código mais seguro.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/a39727491382020fbc275e407b70be045636b123).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
