### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_status_atendido.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#440]
Vulnerability Analysis
Neste código, a principal vulnerabilidade detectada é a falta de sanitização dos dados antes de inseri-los diretamente em uma consulta SQL, o que torna o código vulnerável a ataques de injeção de SQL.

Para corrigir esta vulnerabilidade, é recomendado utilizar declarações preparadas (prepared statements) ao invés de concatenar diretamente os valores na query SQL. Desta forma, os dados são tratados de forma segura, impedindo a execução de comandos maliciosos.

Segue um exemplo de como o código pode ser corrigido:

```php
require_once 'Conexao.php';
$pdo = Conexao::connect();
$status = $_POST["status"];

$sql = "INSERT INTO atendido_status(status) VALUES (:status)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':status', $status);
$stmt->execute();
```

Dessa forma, os dados passados via `$_POST` são devidamente tratados e inseridos de forma segura no banco de dados. Isso aumenta a segurança do código e previne possíveis ataques de injeção de SQL.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@mustafaneto
Vulnerabilidade reportada em: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-j3p8-xww6-wvqh
