### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_situacao.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#441]
Vulnerability Analysis
A vulnerabilidade presente neste código é a chamada SQL Injection. O problema está na forma como a variável `$situacao` é utilizada diretamente na construção da query SQL, sem qualquer tipo de sanatização.

Um atacante mal-intencionado pode explorar essa vulnerabilidade enviando um valor malicioso para a variável `$situacao`, como por exemplo: `'; DROP TABLE situacao; --`. Neste caso, o atacante está enviando um comando SQL adicional que irá deletar a tabela `situacao`.

Para corrigir esta vulnerabilidade, é recomendado utilizar prepared statements ao invés de interpolação de strings na query SQL. Dessa forma, o código corrigido ficaria assim:

```php
prepare($sql);
	$stmt->execute(array(':situacao' => $situacao));
?>
```

Dessa forma, o valor da variável `$situacao` é passada como um parâmetro, evitando assim a vulnerabilidade de SQL Injection. Sempre que possível, é importante utilizar prepared statements para proteger o código contra este tipo de ataque.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/39f362046581385edb3a9b25976c9c1c9ddb5a94).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@mustafaneto
Vulnerabilidade relatada em: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-r8fq-hqr2-v5j9
Corrigido em: https://github.com/LabRedesCefetRJ/WeGIA/commit/e6bfae095258e1200192f15bea68a933e9f310b9
