### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_epi.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#442]
Vulnerability Analysis
A vulnerabilidade presente no código é a possibilidade de injeção de SQL. Isso ocorre devido ao fato de que o valor da variável `$descricao_epi` é diretamente concatenado na query SQL sem nenhum tipo de sanitização ou escape.

Um atacante poderia explorar essa vulnerabilidade através da inserção de dados maliciosos no campo `descricao_epi`, o que poderia levar a execução de comandos SQL indesejados, como inserção, atualização ou exclusão de dados no banco de dados.

Para corrigir essa vulnerabilidade, é recomendado utilizar prepared statements para garantir que os valores sejam tratados de forma segura antes de serem executados na query SQL. Por exemplo, o código corrigido seria algo assim:

```php
require_once 'Conexao.php';
$pdo = Conexao::connect();
$descricao_epi = $_POST["descricao_epi"];

$sql = "INSERT INTO epi (descricao_epi) VALUES (:descricao_epi)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':descricao_epi', $descricao_epi);
$stmt->execute();
```

Dessa forma, o dado inserido no campo `descricao_epi` será tratado de forma segura, sem possibilidade de injeção de SQL.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
