### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_cargo.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#444]
Vulnerability Analysis
O código apresenta uma vulnerabilidade de injeção de SQL. A variável `$cargo` é obtida diretamente do input do usuário ($_POST["cargo"]) e inserida diretamente na query SQL, sem qualquer tipo de sanitização.

Um atacante mal-intencionado poderia explorar essa vulnerabilidade inserindo comandos maliciosos no campo de input, o que poderia comprometer a integridade dos dados no banco de dados ou até mesmo realizar ações prejudiciais.

Para evitar essa vulnerabilidade, recomenda-se utilizar prepared statements em vez de concatenar diretamente os valores na query. Dessa forma, os dados são tratados de forma segura e não permitem a execução de comandos SQL maliciosos. 

Segue um exemplo de como corrigir o código utilizando prepared statements:

```php
require_once 'Conexao.php';
$pdo = Conexao::connect();
$cargo = $_POST["cargo"];

$sql = "INSERT INTO cargo(cargo) VALUES(:cargo)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':cargo', $cargo);
$stmt->execute();
```

Dessa forma, o valor da variável $cargo é tratado de forma segura e não há mais a vulnerabilidade de injeção de SQL.

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade já havia sido corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/0ff4d0c0055273499f7129830a0c59d220b13bd5)

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil

**Comment by nilsonLazarin** [comment]
@mustafaneto, para seu TCC
Vulnerabilidade relatada pela equipe de segurança: https://github.com/LabRedesCefetRJ/WeGIA/security/advisories/GHSA-2775-42rh-535q
Código da vulnerabilidade: 
Correção: https://github.com/LabRedesCefetRJ/WeGIA/commit/f3b1cd90e33b790b6b2049c69d22c6d50fe965a1
