### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/adicionar_beneficios.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#445]
Vulnerability Analysis
Há uma vulnerabilidade de injeção de SQL neste código. A variável `$beneficios`, que é proveniente do input do usuário através do $_POST, é concatenada diretamente na string SQL sem qualquer tipo de sanitização ou validação.

Isso significa que um usuário mal-intencionado pode inserir código SQL malicioso no campo "beneficios" e manipular o banco de dados de forma indesejada. Por exemplo, se o usuário inserir algo como `'DROP TABLE beneficios`, isso resultaria na exclusão da tabela "beneficios" do banco de dados.

Para corrigir essa vulnerabilidade, é altamente recomendável utilizar prepared statements em consulta SQL, que irá separar os dados de entrada do código SQL, evitando assim a injeção de SQL. Abaixo está o código corrigido:

```php
require_once 'Conexao.php';
$pdo = Conexao::connect();
$beneficios = $_POST["beneficios"];

$sql = "INSERT into beneficios(descricao_beneficios) values(:beneficios)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':beneficios', $beneficios);
$stmt->execute();
```

Com a utilização de prepared statements e bindParam, os dados enviados pelo usuário são tratados de forma segura, impedindo que sejam interpretados como instruções SQL maliciosas. Assim, a vulnerabilidade de injeção de SQL é mitigada.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
