### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/pet/PetDAO.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#448]
Vulnerability Analysis
1. A vulnerabilidade nesse código está na forma como o caminho do arquivo de conexão (`dao/Conexao.php`) é determinado. O código primeiro verifica se o arquivo existe no diretório atual e, caso não encontre, começa a subir um nível de diretório por vez até encontrar o arquivo. Esse método pode ser considerado inseguro, pois um atacante pode utilizar o loop para acessar diretórios acima do desejado e potencialmente obter acesso a arquivos sensíveis.

2. Além disso, a prática de ter a conexão com o banco de dados dentro do código da classe `PetDAO` não segue o princípio de separação de preocupações. É recomendado separar a lógica de acesso ao banco de dados em uma classe dedicada, como a `Conexao`, e então injetar essa conexão na classe `PetDAO`.

3. Outra questão é o tratamento de exceções no código. Há blocos try-catch para tratamento de exceções, porém, em alguns casos, apenas a mensagem de erro é exibida na tela, o que pode não ser ideal em um ambiente de produção.

4. Na função `adicionarPet`, a inserção da imagem do pet diretamente no banco de dados como conteúdo binário (`$imgperfil`) pode não ser a melhor prática. Normalmente, armazenar as imagens em um diretório no servidor e salvar somente o caminho da imagem no banco de dados é mais eficiente.

5. Análise de SQL Injection: As consultas SQL no código não estão aproveitando as funções de prepared statements ao máximo. Ainda há concatenação de strings em algumas partes, o que pode tornar o código vulnerável a ataques de SQL Injection.

Estas são algumas áreas que podem ser melhoradas para tornar o código mais seguro, robusto e seguindo as melhores práticas de desenvolvimento.

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
13/09/24
