### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/pet/exibir_especie.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#450]
Vulnerability Analysis
O código apresentado não possui vulnerabilidades de segurança. No entanto, é importante observar que a forma como a conexão com o banco de dados está sendo feita pode ser melhorada. 

Atualmente, o código utiliza a classe Conexao para realizar a conexão com o banco de dados, mas não mostra a implementação dessa classe. É importante garantir que a conexão com o banco de dados seja feita de maneira segura, utilizando práticas recomendadas, como a utilização de prepared statements para evitar SQL Injection. Além disso, é importante garantir que as credenciais de acesso ao banco de dados sejam protegidas de forma adequada.

Além disso, é sempre recomendado validar e sanitizar os dados provenientes do banco de dados antes de utilizá-los. No código apresentado, os dados da consulta SQL são diretamente inseridos no array resultado, o que pode não garantir a integridade dos dados retornados.

Em resumo, apesar de não apresentar vulnerabilidades óbvias, é importante garantir boas práticas de segurança no acesso ao banco de dados e na manipulação dos dados retornados para garantir a segurança e integridade do sistema.

**Comment by angel-jgpv** [comment]
Resolvido By: Lenart
11/09/2024
