### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/pet/exibir_cor.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#451]
Vulnerability Analysis
Este trecho de código possui uma vulnerabilidade de injeção de SQL, pois está inserindo diretamente um comando SQL na variável `$sql` sem fazer uso de prepared statements.

Para corrigir essa vulnerabilidade, recomenda-se o uso de prepared statements para proteger contra ataques de injeção de SQL. Um exemplo de como poderia ser feito:

```php
prepare($sql);
	$stmt->execute();
	$resultado = array();
	while ($row = $stmt->fetch()) {
    	$resultado[] = array('id_cor'=>$row['id_pet_cor'],'cor'=>$row['descricao']);
	}
	echo json_encode($resultado);

?>
```

Neste código corrigido, foi utilizado prepared statements para executar a query de forma segura, evitando assim a vulnerabilidade de injeção de SQL.

**Comment by angel-jgpv** [comment]
Resolvido by: Lenart
06/09/2024
