### ISSUE TITLE
Análise de vulnerabilidade do arquivo dao/pet/adicionar_tipo_exame.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#453]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Falta de verificação e validação dos dados de entrada: O código recebe o valor do campo "tipo_exame" diretamente do formulário sem realizar nenhuma validação ou sanitização. Isso pode permitir a inserção de dados maliciosos no banco de dados. Recomenda-se sempre validar e sanitizar os dados de entrada antes de utilizá-los em consultas SQL.

2. Falta de prepared statements: O código monta a consulta SQL diretamente concatenando a variável $tipo_exame, o que pode abrir brechas para ataques de injeção SQL. Deve-se utilizar prepared statements para evitar esse tipo de vulnerabilidade.

3. Exposição de informações sensíveis na resposta JSON: No final do código, ao utilizar a função `json_encode($p)`, o código está retornando todos os registros da tabela "pet_tipo_exame" em formato JSON. Dependendo do contexto, isso pode expor informações sensíveis da base de dados para usuários não autorizados.

Explicação:
O código apresenta vulnerabilidades relacionadas à segurança devido à falta de validação dos dados de entrada, o uso inadequado de consultas SQL e a exposição de informações sensíveis. Para corrigir essas vulnerabilidades, recomenda-se implementar as seguintes medidas:
- Validar e sanitizar os dados de entrada, garantindo que apenas informações válidas sejam aceitas.
- Utilizar prepared statements para as consultas SQL, evitando a injeção de código malicioso.
- Limitar as informações sensíveis retornadas em respostas JSON para evitar exposição indevida de dados confidenciais.

**Comment by angel-jgpv** [comment]
Resolvido by: Lenart
19/09/24
