### ISSUE TITLE
Análise de vulnerabilidade do arquivo controle/ModuloControle.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#475]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. O código está vulnerável à injeção de SQL, uma vez que se utiliza a função `extract($_REQUEST)` para extrair variáveis do array `$_REQUEST` e criar variáveis locais no escopo da função. Isso pode permitir a um atacante mal-intencionado manipular o conteúdo das variáveis, possibilitando a execução de comandos SQL maliciosos.
2. Não está sendo realizada validação dos dados de entrada. É importante validar e sanitizar os dados recebidos do usuário antes de utilizá-los em consultas a banco de dados ou em comandos que possam causar impacto no sistema.

Explicação sobre a vulnerabilidade:
- A função `extract($_REQUEST)` é utilizada para extrair todas as variáveis do array `$_REQUEST` e criar variáveis locais no escopo da função, com o mesmo nome das chaves do array. Isso pode ser perigoso, pois se o array `$_REQUEST` contiver chaves maliciosas, um atacante poderia manipular essas variáveis de forma não intencionada. Por exemplo, se o array `$_REQUEST` contiver uma chave chamada `recurso` com um valor malicioso, o atacante poderia manipular a consulta ao banco de dados.
- Além disso, a falta de validação dos dados de entrada pode permitir que um atacante forneça dados falsos ou maliciosos, o que pode levar a operações inseguras.

Sugestões de melhoria:
- Evitar o uso da função `extract` e em vez disso, acessar diretamente os valores do array `$_REQUEST` utilizando chaves específicas. Isso torna o código mais seguro e fácil de entender.
- Validar e sanitizar os dados de entrada antes de utilizá-los em consultas a banco de dados ou em operações críticas. Isso pode incluir a verificação do tipo de dado esperado, a aplicação de filtros de limpeza (por exemplo, `filter_var`), entre outras técnicas de validação.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 4 = Fácil
