### ISSUE TITLE
Análise de vulnerabilidade do arquivo controle/DescricaoControle.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#486]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. **Possível SQL Injection**: Na função `incluir`, o código faz uso da função `extract($_REQUEST)` para criar variáveis a partir dos parâmetros passados na requisição. Isso pode deixar o código vulnerável a ataques de SQL Injection, pois os valores dos parâmetros não são filtrados ou validados antes de serem usados no código.
2. **Não verificação de entrada de dados**: O código não valida ou filtra os dados recebidos como entrada antes de utilizá-los. Isso pode deixar o código vulnerável a ataques como XSS (Cross-Site Scripting) e SQL Injection, dependendo de como os dados são manipulados.
3. **Variável `ROOT` não definida**: O código faz uso da constante `ROOT` para incluir os arquivos necessários, porém a origem dessa constante não está clara no código apresentado. Se a constante não for definida ou não for definida corretamente, isso pode causar erro de inclusão dos arquivos.

Recomendações:
- Certifique-se de filtrar e validar todos os dados recebidos como entrada, especialmente aqueles provenientes do usuário.
- Evite o uso da função `extract($_REQUEST)` para criar variáveis a partir dos parâmetros da requisição. Em vez disso, acesse diretamente os valores do array `$_REQUEST` com as chaves específicas.
- Defina a constante `ROOT` de forma correta e verifique se está sendo incluída antes de utilizar no código. Isso pode ajudar a evitar erros de inclusão de arquivos.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 4 = Útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil

**OBS:** A constante `ROOT` é definida no arquivo de `config.php`
