### ISSUE TITLE
Análise de vulnerabilidade do arquivo controle/AvisoNotificacaoControle.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#490]
Vulnerability Analysis
Vulnerabilidades encontradas:

1. **Inclusão do arquivo de configuração**: O código inclui um arquivo de configuração (`config.php`) sem verificar se o mesmo está fora do diretório especificado. Isso pode permitir a inclusão de arquivos arbitrários (LFI - Local File Inclusion) caso um usuário mal-intencionado consiga controlar o caminho do arquivo a ser incluído.

2. **Tratamento de exceções**: As exceções estão sendo capturadas, porém apenas a mensagem de erro está sendo capturada e não está sendo tratada de forma adequada. Em caso de erro, o código apenas exibe a mensagem de erro, o que pode expor informações sensíveis ou permitir que o erro não seja tratado corretamente.

3. **Manipulação de dados não filtrados**: Na função `mudarStatus`, o código está extraindo o valor de `$_POST['id_notificacao']` diretamente, sem fazer nenhuma validação e/ou filtragem dos dados. Isso pode abrir brechas para ataques de injeção de SQL, principalmente se os dados não forem validados antes de serem utilizados em consultas ao banco de dados.

Recomendações:

1. **Incluir arquivos de forma segura**:
   - Verificar se o arquivo a ser incluído está dentro do diretório permitido.
   - Utilizar caminhos absolutos ou controlados para incluir arquivos.

2. **Tratamento correto de exceções**:
   - Além de exibir a mensagem de erro, é importante tomar alguma ação corretiva, como logar o erro, exibir mensagens adequadas ao usuário ou redirecionar para uma página de erro personalizada.

3. **Filtrar e validar dados de entrada**:
   - Sempre validar e filtrar os dados de entrada, especialmente quando são provenientes de fontes externas (como formulários) antes de utilizá-los em consultas ao banco de dados.

Cada uma dessas vulnerabilidades apresenta um risco significativo de segurança e deve ser corrigida o mais rápido possível para mitigar possíveis ataques e garantir a segurança do sistema.

**Comment by GabrielPintoSouza** [comment]
Validação dos dados de entrada foi adicionada no seguinte [commit]
(https://github.com/nilsonLazarin/WeGIA/commit/8a206defffd3aa0135956d5615c14f0c9134bab8)

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 4 = Útil
- O erro foi fácil de localizar? 5 = Muito Fácil
- Foi possível corrigir? Parcialmente
- O quão fácil de corrigir? 5 = Muito fácil

**OBS:** A utilização do arquivo `config.php` é padrão em todo o projeto, alterar sua utilização implicaria em uma refatoração em quase todos os arquivos do sistema.
