### ISSUE TITLE
Análise de vulnerabilidade do arquivo controle/AlmoxarifeControle.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#495]
Vulnerability Analysis
1. Vulnerabilidade de Injeção de SQL:

Na classe AlmoxarifeControle, o código está utilizando a função `extract($_REQUEST)` para extrair os parâmetros da requisição HTTP e transformá-los em variáveis locais. Isso pode ser perigoso se os valores dos parâmetros não forem devidamente validados, pois pode abrir brechas para ataques de injeção de SQL.

Por exemplo, na função `excluir()`, o parâmetro `$id_almoxarife` está sendo utilizado diretamente, sem nenhuma validação prévia. Isso poderia permitir que um usuário mal intencionado enviasse um valor manipulado que levasse a uma injeção de SQL.

Para corrigir essa vulnerabilidade, é importante que os parâmetros sejam validados e sanitizados antes de serem utilizados em consultas ao banco de dados. Uma forma segura de fazer isso é utilizando prepared statements em conjunto com declarações preparadas.

Além disso, é recomendável evitar o uso da função `extract()` para lidar com os parâmetros da requisição, pois pode tornar o código mais vulnerável a ataques. Em vez disso, é recomendável acessar diretamente os parâmetros da requisição, utilizando `$_REQUEST['nome_do_parametro']`. Isso torna mais claro de onde vêm os dados e permite uma melhor validação dos mesmos.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 4 = Útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
