### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Situacao.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#525]
Vulnerability Analysis
A vulnerabilidade neste código é que a propriedade `$id_situacao` está sendo definida como privada, mas não está sendo utilizada em nenhum lugar na classe. Isso pode indicar um descuido na implementação da classe, já que a propriedade não está sendo utilizada para armazenar nenhum valor.

Para corrigir essa vulnerabilidade, podemos remover a propriedade `$id_situacao` e os métodos `getId_situacao` e `setId_situacao` associados a ela, já que não estão sendo utilizados neste contexto. Dessa forma, simplificamos a classe e removemos código desnecessário.

Aqui está a versão corrigida da classe `Situacao`:

```php
class Situacao
{
    private $situacoes;
   
    public function __construct($situacoes)
    {
        $this->situacoes = $situacoes;
    }

    public function getSituacoes()
    {
        return $this->situacoes;
    }

    public function setSituacoes($situacoes)
    {
        $this->situacoes = $situacoes;
    }
}
```

Dessa forma, a classe ficará mais limpa e sem código desnecessário.

**Comment by GabrielPintoSouza** [comment]
A propriedade `$id_situacao` é utilizada em outros arquivos do código.
