### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Saude.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#528]
Vulnerability Analysis
A vulnerabilidade no código acima está relacionada à ausência de validação de dados de entrada nos métodos de setter. Para garantir a integridade dos dados, é importante validar e/ou sanitizar os valores recebidos antes de atribuí-los às propriedades da classe.

Para corrigir essa vulnerabilidade, você pode adicionar validações nos métodos setters, de acordo com as regras de negócio da sua aplicação. Por exemplo, validar se o texto não está vazio, se a enfermidade é um valor válido, se a data de diagnóstico está em um formato correto, etc. Isso ajudará a prevenir possíveis erros e falhas de segurança no sistema.

Além disso, também recomenda-se o uso de filtros de entrada, como filtros de validação ou sanitização, para garantir que os dados fornecidos pelo usuário estejam de acordo com o esperado. Você pode utilizar funções como `filter_var` para filtrar e validar entradas de forma mais segura.

Por fim, também é importante lembrar de habilitar o modo de exibição de erros em desenvolvimento para facilitar a identificação de possíveis vulnerabilidades e erros no código. Você pode fazer isso adicionando as seguintes linhas no início do seu script PHP:

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

Dessa forma, você poderá identificar e corrigir problemas no código de forma mais eficiente.

**Comment by FlameOff** [comment]
Código atualizado no arquivo com problema
