### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Produto.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#531]
Vulnerability Analysis
Vulnerabilidades encontradas:
1. Não há validações nos métodos de set para garantir a integridade dos dados. Por exemplo, é possível atribuir um preço negativo a um produto, o que não faz sentido.
2. Falta de tratamento de erros ao definir os valores dos atributos. Caso haja uma tentativa de definir um valor inválido para um atributo, não há um mecanismo para lidar com isso.
3. A propriedade `$id_categoria_produto` está definida na classe, mas não é utilizada em nenhum lugar.

Sugestões de melhorias:
1. Adicionar validações nos métodos de set para garantir que os valores estejam dentro de um intervalo válido. Por exemplo, para o preço, pode ser verificado se é um número positivo.
2. Implementar tratamento de erros para lidar com valores inválidos atribuídos aos atributos, lançando uma exceção ou retornando uma mensagem de erro.
3. Remover a propriedade `$id_categoria_produto` se não for utilizada em nenhum lugar, a fim de manter o código mais limpo e evitar confusões.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 2 = Não muito fácil

**OBS**: Apesar do processo de correção não ser complexo, ele envolveu a refatoração de diversos outros arquivos não mencionados na issue.
