### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Funcao.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#551]
Vulnerability Analysis
Não foi encontrada nenhuma vulnerabilidade no código fornecido.  
A classe `Funcao` parece estar corretamente definida, com dois atributos privados: `$idfuncao_voluntario` e `$descricao_funcao`. Como esses atributos são privados, eles só podem ser acessados dentro da própria classe `Funcao`, o que é uma prática recomendada para proteger os dados e garantir o encapsulamento.  
Se houver mais código relacionado à classe `Funcao` que não foi fornecido, é importante verificar o uso correto desses atributos e se a classe está sendo utilizada adequadamente em seu contexto.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 2 = Não muito útil
- O erro foi fácil de localizar? 5 = Muito fácil 
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil

**OBS:** Segundo a issue não existia erro, porém os atributos estavam inacessíveis, não existindo métodos acessores como `get`e `set`
