### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Documento.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#556]
Vulnerability Analysis
Não foram encontradas vulnerabilidades no código fornecido. O código está bem estruturado, seguindo os princípios de encapsulamento e coesão. No entanto, é importante lembrar de sempre validar e limpar quaisquer dados de entrada, como os parâmetros passados para o construtor da classe `Documento`. Isso ajuda a prevenir possíveis vulnerabilidades, como ataques de Injeção de Dados.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 4 = Útil
- O erro foi fácil de localizar? = 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 4 = Fácil
