### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Categoria.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#560]
Vulnerability Analysis
A vulnerabilidade no código acima está na falta de validação dos dados de entrada no construtor da classe Categoria. Ao simplesmente atribuir o valor recebido para a propriedade `$descricao_categoria`, não há verificação se o valor passado é válido ou se está vazio.

Para corrigir isso, é recomendável adicionar validações para garantir que o valor passado para o construtor seja do tipo esperado e não esteja vazio. Por exemplo, podemos adicionar uma verificação para garantir que o valor passado não seja uma string vazia:

```php
public function __construct($descricao_categoria){
    if (!is_string($descricao_categoria) || empty($descricao_categoria)) {
        throw new InvalidArgumentException("A descrição da categoria deve ser uma string não vazia.");
    }
    $this->descricao_categoria = $descricao_categoria;
}
```

Dessa forma, ao tentar instanciar um objeto Categoria com uma descrição inválida, como uma string vazia, será lançada uma exceção, impedindo a criação do objeto com dados inválidos.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 3 = Relativamente fácil

**OBS**: Apesar da correção não ser complexa, ela envolveu a refatoração de outros arquivos que não foram mencionados na issue.
