### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/AvisoNotificacao.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#568]
Vulnerability Analysis
1. Vulnerabilidade no construtor da classe `AvisoNotificacao`:  

O código possui uma vulnerabilidade no construtor da classe `AvisoNotificacao`. Ao receber um parâmetro do tipo `Aviso` e tentar acessar o método `getIdFuncionario()` desse objeto para preencher a propriedade `idFuncionario`, o código está assumindo que a classe `Aviso` possui esse método, sem a devida verificação. No entanto, no código fornecido, a classe `Aviso` não possui o método `getIdFuncionario()`, o que pode levar a erros em tempo de execução.

Para corrigir essa vulnerabilidade, é importante verificar se o método existe no objeto antes de tentar acessá-lo. Uma opção seria verificar se o objeto `Aviso` possui um método `getIdFuncionario()` antes de acessá-lo.

Exemplo de como corrigir a vulnerabilidade: 

```php
public function __construct(Aviso $aviso)
{
    $this->setIdAviso($aviso->getIdAviso());
    if (method_exists($aviso, 'getIdFuncionario')) {
        $this->setIdFuncionario($aviso->getIdFuncionario());
    }
    $this->setStatus(true);
}
``` 

Dessa forma, o código estará mais seguro contra possíveis erros de execução devido à inexistência do método `getIdFuncionario()` na classe `Aviso`.

**Comment by GabrielPintoSouza** [comment]
Uma instância da classe Aviso sempre possuirá o método getIdFuncionario().
