### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Aviso.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#569]
Vulnerability Analysis
1. Vulnerabilidade encontrada: Falta de validação de dados na classe Aviso.

Explicação: O código não possui nenhuma validação dos dados passados para o construtor da classe Aviso. É importante garantir a integridade dos dados, verificando se os parâmetros recebidos são do tipo esperado e se não estão vazios ou incorretos. Caso contrário, a aplicação pode apresentar comportamentos inesperados ou vulnerabilidades de segurança.

Recomendação: Adicionar validações nos parâmetros recebidos no construtor da classe Aviso. Por exemplo, verificar se os IDs são inteiros positivos e se a descrição não está vazia. Caso alguma validação falhe, é importante lançar uma exceção ou retornar um erro apropriado.

Exemplo de como adicionar validações nos parâmetros do construtor:

```php
public function __construct($idFuncionario, $idPessoaAtendida, $descricao)
{
    if (!is_int($idFuncionario) || $idFuncionario <= 0) {
        throw new InvalidArgumentException('ID do funcionário inválido.');
    }
    if (!is_int($idPessoaAtendida) || $idPessoaAtendida <= 0) {
        throw new InvalidArgumentException('ID da pessoa atendida inválido.');
    }
    if (empty($descricao)) {
        throw new InvalidArgumentException('Descrição não pode ser vazia.');
    }

    $this->setIdFuncionario($idFuncionario);
    $this->setIdPessoaAtendida($idPessoaAtendida);
    $this->setDescricao($descricao);
}
```

**Comment by GabrielPintoSouza** [comment]
Vulnerabilidade corrigida no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/237bab536f866884ad3565bed3db1d4ee05ed25a).

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 4 = Fácil
