### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/Almoxarifado.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#574]
Vulnerability Analysis
Vulnerabilidade encontrada:  
- O construtor da classe `almoxarifado` recebe um parâmetro `$descricao_almoxarifado` e atribui diretamente à propriedade `descricao_almoxarifado`, sem realizar uma validação ou sanitização dos dados. Isso pode resultar em possíveis vulnerabilidades de segurança, como injeção de código malicioso.

Para corrigir essa vulnerabilidade, é recomendado realizar a validação e sanitização dos dados recebidos no construtor. Uma abordagem comum é utilizar filtros ou regular expressions para garantir que os dados recebidos são seguros antes de atribuí-los às propriedades da classe. Além disso, a utilização de prepared statements em consultas SQL pode ajudar a prevenir ataques de injeção de SQL.

Exemplo de correção da vulnerabilidade no construtor:
```php
public function __construct($descricao_almoxarifado)
{
    // Validar e sanitizar o parâmetro $descricao_almoxarifado
    $descricao_almoxarifado = filter_var($descricao_almoxarifado, FILTER_SANITIZE_STRING);

    $this->descricao_almoxarifado = $descricao_almoxarifado;
}
``` 

Ao aplicar a correção acima, os dados do parâmetro `$descricao_almoxarifado` serão validados e sanitizados antes de serem atribuídos à propriedade da classe, proporcionando uma camada adicional de segurança.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O Comentário foi útil? 5 = Muito útil
- O erro foi fácil de lozalicar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O Quão fácil de corrigir? 3 = Relativamente fácil

**OBS**: Apesar da correção não ser complexa, ela envolveu a refatoração de outros arquivos não mencionados na issue
