### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/memorando/Memorando.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#579]
Vulnerability Analysis
O código apresentado não possui vulnerabilidades graves. No entanto, há uma pequena melhoria que pode ser feita no método setData():

Atualmente, o método setData() está definido sem parâmetros. No entanto, ao chamar esse método, ele sempre define a data atual, o que pode limitar a flexibilidade de usar a classe Memorando em diferentes contextos.

Para permitir que a data seja definida manualmente, você pode adicionar um parâmetro opcional ao método setData() para receber a data desejada. Caso nenhum valor seja passado, ele continuará a definir a data atual. Aqui está como você pode atualizar o método:

```php
public function setData($data = null)
{
    if($data){
        $this->data = $data;
    } else {
        date_default_timezone_set('America/Sao_Paulo');
        $dataAtual = date('Y-m-d H:i:s');
        $this->data = $dataAtual;
    }
}
```

Essa pequena alteração permitirá a flexibilidade de definir uma data específica, se necessário, ao mesmo tempo em que mantém a funcionalidade de definir a data atual se nenhum valor for passado.

**Comment by GabrielPintoSouza** [comment]
# Feedback
- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 5 = Muito fácil
