### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/memorando/Despacho.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#580]
Vulnerability Analysis
Vulnerabilidades encontradas no código:

1. Falta de validação de entrada: O construtor da classe `Despacho` recebe um parâmetro `$texto`, mas não há validação para garantir que o valor recebido é do tipo esperado (string).

2. Setter `setData` mal implementado: O método `setData` não recebe nenhum parâmetro para definir a data do despacho. Além disso, a implementação da data utiliza `date_default_timezone_set('America/Sao_Paulo')`, o que pode não refletir a timezone correta do servidor. Seria mais adequado receber a data como parâmetro ou utilizar a data do servidor de forma confiável.

3. Métodos setId_Despacho e setId_Memorando com nomenclatura inconsistente: Os métodos `setId_Despacho` e `setId_Memorando` estão com nomenclatura inconsistente, o ideal seria seguir um padrão de nomenclatura, como camelCase.

4. Métodos setId_remetente e setId_destinatario com nomenclatura incorreta: Os métodos `setId_remetente` e `setId_destinatario` estão com nomenclatura incorreta, deveriam seguir o padrão de camelCase.

5. Atributos não sendo utilizados no construtor: Os atributos `$id_despacho`, `$id_memorando`, `$id_remetente` e `$id_destinatario` não estão sendo inicializados no construtor da classe, o que pode resultar em valores nulos caso não sejam definidos posteriormente.

Sugestões de melhorias:
- Adicionar validação de entrada no construtor para garantir que o parâmetro `$texto` seja do tipo string.
- Melhorar a implementação do método `setData` para receber a data como parâmetro ou utilizar a data do servidor de forma confiável.
- Corrigir a nomenclatura dos métodos `setId_Despacho`, `setId_Memorando`, `setId_remetente` e `setId_destinatario` para seguir um padrão de nomenclatura consistente.
- Inicializar os atributos `$id_despacho`, `$id_memorando`, `$id_remetente` e `$id_destinatario` no construtor da classe.

**Comment by GabrielPintoSouza** [comment]
# Feedback

- O comentário foi útil? 5 = Muito útil
- O erro foi fácil de localizar? 5 = Muito fácil
- Foi possível corrigir? Sim
- O quão fácil de corrigir? 3 = Relativamente fácil

**OBS:** Apesar da correção não ser complexa, ela envolveu a refatoração de diversos outros arquivos além do original mencionado na issue.
