### ISSUE TITLE
Análise de vulnerabilidade do arquivo classes/memorando/Anexo.php

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#581]
Vulnerability Analysis
O código apresentado não possui vulnerabilidades de segurança, pois se trata de uma simples classe em PHP para representar um anexo. No entanto, é importante ressaltar que a classe Anexo não possui validações de entrada de dados, o que poderia resultar em vulnerabilidades caso os dados não sejam tratados corretamente antes de serem atribuídos às propriedades da classe.

Para melhorar a segurança e robustez do código, seria recomendável adicionar validações nos métodos de set para garantir que os dados atribuídos às propriedades da classe sejam seguros e válidos. Por exemplo, poderiam ser feitas validações para conferir o tipo de dados, tamanho máximo permitido, entre outros.

Além disso, em um sistema real, outras medidas de segurança como a sanitização de dados, verificação de permissões de acesso, controle de sessão e criptografia também seriam necessárias para proteger a aplicação contra possíveis vulnerabilidades.

**Comment by GabrielPintoSouza** [comment]
Validações de entrada adicionadas no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/a727972ce65880c1fea495ef1314e153f9148581)

Qual seria o tamanho máximo permitido para um arquivo?

**Comment by Davi220506** [comment]
Adicionei verificações para evitar problemas de vulnerabilidades de segurança
