### ISSUE TITLE
Observações sobre cadastrar atendido

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#588]
Podemos adicionar o mesmo atendido duas ou mais vezes.

O atendido pode ter data de nascimento inválida, como 01/03/1700 ou até mesmo a data atual do dia em que foi cadastrado.

**Comment by GabrielPintoSouza** [comment]
## Possibilidade de correção pelo banco de dados

Uma maneira rápida e "fácil" de corrigir esse problema é atribuir aos campos `pessoa_id_pessoa` e `cpf` das tabelas `atendido` e `pessoa`, respectivamente, o comportamento de *UNIQUE* e posteriormente tratar possíveis exceções via código.

Creio ser a maneira ideal, porém envolve modificações na base de dados da aplicação em produção. @nilsonLazarin .

**Comment by GabrielPintoSouza** [comment]
Data mínima e máxima de nascimento adicionada no seguinte [commit](https://github.com/nilsonLazarin/WeGIA/commit/452b9197398eac01fe4a2d108af223ff798f5a81).

**Comment by nilsonLazarin** [comment]
@joaopontes22, favor verificar novamente.

O erro relatado não ocorreu comigo. Prepare um vídeo ou o passo-a-passo pra ocorrência do bug.

![image](https://github.com/nilsonLazarin/WeGIA/assets/32855001/d8305545-c71f-4bb5-966b-7710a08d69c5)

**Comment by nilsonLazarin** [comment]
Já resolvido.
