### ISSUE TITLE
Observações sobre a seção Editar ficha médica do pet cadastrado.

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#597]
https://demo.wegia.org/html/pet/profile_pet.php?id_pet=1

As alterações especificamente feitas nas opções Vermifugado e Vacinado(apenas mudando da condição de Sim para não), não estão sendo salvas ao clicar para salvar as alterações.

![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/1223104f-a0ac-43f0-9f6a-64aaae067c49)

![Captura de tela 2024-06-07 101547](https://github.com/nilsonLazarin/WeGIA/assets/105460138/b11716e6-8014-450e-a335-214b4beb5af2)

**Comment by nilsonLazarin** [comment]
@angel-jgpv outros erros estão ocorrendo durante a criação de uma ficha médica para o PET

**Comment by angel-jgpv** [comment]
Resolvi o problema de não salvamento das alterações, porém ainda estou enfrentando o mesmo erro de redirecionamento de url.

**Comment by angel-jgpv** [comment]
Resolvido By Lenart
01.11.24
