### ISSUE TITLE
Observações sobre registrar entrada

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#599]
Ao selecionar os almoxarifados na opção de registrar entrada, os almoxarifados criados não aparecem como opção.
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/931f607f-ce9b-4f40-908c-9ee30645f81e)

Isso compromete o registro de entradas pois o almoxarifado é requerido para que o registro seja feito:
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/f0c3bc51-48f6-4798-ad38-53774eb0ea12)

Aqui a prova de que os almoxarifados foram criados mesmo:
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/fed15d44-dbab-450b-bc22-c7a0779dafd5)

**Comment by GabrielPintoSouza** [comment]
O Almoxarifado só aparece se o seu usuário estiver registrado como Almoxarife daquele respectivo almoxarifado, por favor fazer o teste novamente após se registrar como almoxarife em `Configurações > Permissões > Adicionar Almoxarife`

**Comment by joaopontes22** [comment]
Resolvido

**Comment by joaopontes22** [comment]
Resolvido 04/09/2024
