### ISSUE TITLE
Problema ao excluir um Atendido [Parar de mexer até a reunião]

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#6]
Ao clicar em Excluir de um perfil atendido, o mesmo exibe um alerta pedindo pela confirmação da exclusão, ao clicar em confirmar ele redireciona o usuário para a página "/html/atendido/Informacao_Atendido.php", que exibe a listagem dos atendidos, contudo não executa a remoção do banco de dados

**Comment by nilsonLazarin** [comment]
@GabrielPintoSouza demonstre esse erro na próxima reunião.

**Comment by GabrielPintoSouza** [comment]
Error: na tabela pessoas = call excluiratendido(:idatendido)

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wegia`.`saude_enfermidades`, CONSTRAINT `fk_daude_enfermidades_saude_fichamedica1` FOREIGN KEY (`id_fichamedica`) REFERENCES `saude_fichamedica` (`id_fichamedica`) ON DELETE NO ACTION ON UPDA)
