### ISSUE TITLE
Observações sobre registrar saída

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#600]
Ao clicar pra registrar um novo produto na página Registrar Saída, o usuário clica no '+' azul e é redirecionado para a página em que o produto é criado
![Captura de tela 2024-06-12 074753](https://github.com/nilsonLazarin/WeGIA/assets/105460138/752ee72b-8e01-484f-a918-18f947f8c5c0)

Porém, ao clicar no botão VOLTAR somos redirecionados para a página de Registrar Entrada, o que não deveria acontecer

![Captura de tela 2024-06-12 074821](https://github.com/nilsonLazarin/WeGIA/assets/105460138/b01fd559-b407-4c5f-9bf8-cd5c176ae2c5)

Além disso, os produtos registrados não aparecem para serem selecionados na opção de selecioná-los na página Registrar Saída

![Captura de tela 2024-06-12 074920](https://github.com/nilsonLazarin/WeGIA/assets/105460138/d0711ee5-76cc-441b-bf85-1b69ab34e667)

Já na página Registrar Entrada está funcionando corretamente, os produtos registrados aparecem listados para selecionar

![Captura de tela 2024-06-12 074936](https://github.com/nilsonLazarin/WeGIA/assets/105460138/f34d6beb-a259-4ca4-9ea1-53f58e723345)

**Comment by GabrielPintoSouza** [comment]
**Informação Extra:** Ao selecionar um almoxarifado, o produto retornado pelo autocomplete é considerado inválido.

**Comment by joaopontes22** [comment]
Resolvido 04/09/2024
