### ISSUE TITLE
Observações sobre Listar Almoxarifados

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#601]
Não sei a causa, mas certos almoxarifados não estão sendo deletados ao clicar no ícone de excluir. O que não faz sentido já que eu consegui excluir alguns antes. A única ação que fiz com eles foi registrar entradas.

![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/05cd9e67-d1e4-4985-92db-cbe2b339288b)

**Comment by GabrielPintoSouza** [comment]
Provavelmente deve fazer parte da regra de negócios não permitir a exclusão de almoxarifados que possuem algum tipo de registro.

**Comment by nilsonLazarin** [comment]
@joaopontes22 verifique se este comportamento está correto.
Se algum almoxarifado tiver algum lançamento ele não deve ser apagado.
Se o almoxarifado não tiver lançamentos ele pode ser apagado.

**Comment by joaopontes22** [comment]
@nilsonLazarin correto, almoxarifados com lançamentos não podem ser apagados.

**Comment by GabrielPintoSouza** [comment]
@joaopontes22 Vou estar encerrando essa issue então, uma vez que o comportamento está dentro do esperado.
