### ISSUE TITLE
Observações sobre Gerar boleto/carnê

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#608]
Coloquem um limite no número de parcelas: 
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/0c74cdc6-02ad-4dac-a4f5-5fffb5a78693)

Apesar da mensagem de erro ao criar o carnê, ele ainda é gerado: 
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/83af01db-0304-409a-a440-1b2e0180a086)

Sugestão: nem dar a opção do usuário digitar valores negativos nos campos 
![Captura de tela 2024-06-19 125636](https://github.com/nilsonLazarin/WeGIA/assets/105460138/0d7c95f8-1222-49e8-9a1f-3b3dbe2a671a)

**Comment by GabrielPintoSouza** [comment]
Resolvidos nos seguintes commits: [commit 1](https://github.com/nilsonLazarin/WeGIA/commit/63ec8998c4b2a39384a95b43654242211cbd6fa4), [commit 2](https://github.com/nilsonLazarin/WeGIA/commit/4ea4160b9858046134366e3d7248b47027184496)
