### ISSUE TITLE
Configuração Contribuição

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#615]
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/c416ead9-8cff-490c-9130-f0dd572db7dd)

Não pude testar essa parte do sistema por falta de funcionalidade do botão 'Cadastre sua Instituição...'

![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/7b885228-0008-46bf-98e3-061c302486bc)

Também não consegui testar a parte de cartão de crédito por estar incompleta

**Comment by GabrielPintoSouza** [comment]
O módulo de Contribuição está sendo refatorado, os painéis de controle não serão mais ou mesmos descritos na issue.
