### ISSUE TITLE
Botão de adicionar grupo no cadastro de sócio

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#622]
Pelo menos na minha branch, o botão '+' que deveria direcionar pra uma página pra criar um grupo pro sócio que está sendo cadastrado não está funcionando ao ser clicado: 
![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/34d73924-efd9-4d49-84c5-80131c305d47)

**Comment by GabrielPintoSouza** [comment]
Resolvi esse problema ontem na minha branch, a solução deve ficar disponível assim que solicitar um pull request para a pre-release.
