### ISSUE TITLE
Letras onde era pra ter número: 

### ISSUE THREAD

**Issue by joaopontes22** [nilsonLazarin/WeGIA#625]
Ao cadastrar um funcionário e selecionar o gênero masculino, podemos colocar letras nas opções que deviam aceitar apenas números.

![image](https://github.com/nilsonLazarin/WeGIA/assets/105460138/faaca700-81e8-45e4-bd10-270d64081be8)

**Comment by GabrielPintoSouza** [comment]
Adicionada para os campos de input a função `Onlynumbers()` que é ativada com o evento `onkeypress`.
