### ISSUE TITLE
Problema ao registrar a doação de um funcionário que não possuí dados sobre seu endereço

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#647]
Ao registrar a doação, os dados informados na view não são registrados no banco de dados, ocasionando em um erro na API.

**Pergunta**: Um usuário, sem autenticação no sistema, deve ser capaz de mudar os dados de um funcionário apenas informando o CPF do mesmo?

**Comment by nilsonLazarin** [comment]
@GabrielPintoSouza uma camada adicional de segurança deverá ser implementada nesse caso.
