### ISSUE TITLE
Problemas em emitir um boleto na pre-master

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#677]
[Wed Aug 21 13:42:04.285721 2024] [php:error] [pid 494] [client 10.0.0.254:58202] PHP Fatal error:  Uncaught Error: Class "Conexao" not found in /var/www/html/WeGIA/html/contribuicao/doacao/model/emitirBoleto.php:24\nStack trace:\n#0 {main}\n  thrown in /var/www/html/WeGIA/html/contribuicao/doacao/model/emitirBoleto.php on line 24, referer: https://dev.wegia.org:8100/WeGIA/html/contribuicao/doacao/index.php

**Comment by GabrielPintoSouza** [comment]
**OBS:** A mesma branch na demo, emite erro 401 como retorno da API ao invés do erro acima. Na máquina local não foi possível a reprodução do erro.

**Comment by nilsonLazarin** [comment]
@GabrielPintoSouza foram realizados ajustes no script de atualização diário.
