### ISSUE TITLE
Requisições no módulo de Material e Patrimônio

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#707]
- Ser possível alterar uma entrada ou saída, de forma que caso um erro ocorra, o colaborador possa alterar a quantidade.
- Ser possível excluir uma entrada ou saída equivocada.
- Adicionar nos relatórios de entrada e saída a data equivalente a cada uma das entradas ou saídas realizadas
- Nos relatórios de entrada e saída, quando selecionado um período, a data do resumo das opções do relatório está em formato americano, passar para brasileiro.

**Comment by nilsonLazarin** [comment]
Reavaliar em reunião
