### ISSUE TITLE
Problema em administrar um medicamento no paciente

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#708]
Ao tentar acessar a página de administração de medicações, recebemos o erro de `ERR_TOO_MANY_REDIRECTS`

**Comment by GabrielPintoSouza** [comment]
[Resolução da issue 708](https://github.com/nilsonLazarin/WeGIA/commit/480bc566b615c5e685eaf98f4a54c44da0a5d8c5)

**Comment by FlameOff** [comment]
O motivo da troca foi a sugestão de correção da issue feita por outro estagiário @joaopontes22, que fez o comentário na issue dizendo o que deveria ser trocado para melhorar o código. Esse foi meu motivo

**Comment by FlameOff** [comment]
E lembrando que a culpa não é dele por o código ter dado erro, a culpa é minha por ter corrigido sem analisar se a correção iria dar problema

**Comment by GabrielPintoSouza** [comment]
> O motivo da troca foi a sugestão de correção da issue feita por outro estagiário @joaopontes22, que fez o comentário na issue dizendo o que deveria ser trocado para melhorar o código. Esse foi meu motivo

Entendi, o uso da $_SESSION realmente é estranho em algumas partes do código, mas quando vamos fazer uma alteração devemos acompanhar todo o fluxo do código para ver em quais lugares vamos ter que fazer alterações complementares.

Sugiro que que use o `ctrl + shift + f` e coloque `$_SESSION['nomeParametro']` para ver todos os lugares que ele ocorre e fazer as devidas alterações de maneira que não quebre a lógica original do código, ai você pode realiza as modificações sugeridas.

Sobre o uso do $_POST: as variáveis globais `$_POST`, `$_GET` e `$_REQUEST` são arrays que guardam conjuntos de chave valor de requisições feitas ao servidor da aplicação, então antes de utilizar uma delas você deve acompanhar a lógica do fluxo do código, caso os dados estejam vindo do front-end o uso de $_GET ou $_POST é válido, contudo se os dados estiverem vindo de alguma `query do próprio servidor` não existe essa necessidade, você pode instanciar uma variável e fazer a atribuição por chamada de função: `$nomeVariavel = $controladoraEspecifica->chamadaDaFuncao()`
