### ISSUE TITLE
Formato da data no relatório de entrada e saída

### ISSUE THREAD

**Issue by nilsonLazarin** [nilsonLazarin/WeGIA#712]
Migrado da Issue #707 

_Nos relatórios de entrada e saída, quando selecionado um período, a data do resumo das opções do relatório está em formato americano, passar para brasileiro._

@GabrielPintoSouza favor especificar com print para facilitar o entendimento.

**Comment by GabrielPintoSouza** [comment]
Na página `html/relatorio_geracao.php`, modificar as informações `A partir de:` e `Até:` para que a data esteja no formato brasileiro.
![relatorio_geracao](https://github.com/user-attachments/assets/d26393c2-3d19-4c49-b46d-5d3316812b5d)

**Comment by Davi220506** [comment]
Resolvido!
![2](https://github.com/user-attachments/assets/6951d090-7ca8-40d4-8967-50590d2c7bbc)
