### ISSUE TITLE
No módulo pet, no arquivo cadastro_pet.php, no fim da página há um quadrado branco, mas especificamente abaixo do botão salvar

### ISSUE THREAD

**Issue by Davi220506** [nilsonLazarin/WeGIA#762]
![Captura de tela de 2024-10-23 14-39-53](https://github.com/user-attachments/assets/aa5ea21b-0de3-41d2-bc2b-0e2484194ce6)

**Comment by angel-jgpv** [comment]
Resolvido by: Lenart
23/10/2024

**Comment by angel-jgpv** [comment]
Resolvido by: Lenart
23/10/2024
