### ISSUE TITLE
404 Not Found na edição de pet em "profile_pet.php"

### ISSUE THREAD

**Issue by Davi220506** [nilsonLazarin/WeGIA#763]
Ao tentar alterar alguma característica de algum pet em "profile_pet.php" ocorre o erro 404 not found

**Comment by angel-jgpv** [comment]
![urlOrigin](https://github.com/user-attachments/assets/41d72acc-fdb7-46c0-92dd-56bf4b9efca8)
![UrlErrada](https://github.com/user-attachments/assets/c50f86dd-c0cc-4a9c-90f7-6439e6da513e)

Após editarmos quaisquer características de um pet,somos redirecionados para esta url que não leva a lugar nenhum, por isso o erro. Navegando pelos respectivos arquivos [profile_pet.php e petControl.php] não consegui encontrar nenhum erro com as urls.

**Comment by angel-jgpv** [comment]
Resolvido by Lenart
1.11.24
