### ISSUE TITLE
Erro ao tentar adicionar a adoção de um pet

### ISSUE THREAD

**Issue by Davi220506** [nilsonLazarin/WeGIA#766]
Ao adicionarmos a adoção de um pet em **"profile_pet.php"**, retorna o seguinte erro:

![Captura de tela de 2024-10-31 16-28-39](https://github.com/user-attachments/assets/bad4a3a6-8022-456f-bdb1-60469def061f)

**Comment by angel-jgpv** [comment]
Erro de redirecionamento de url

**Comment by angel-jgpv** [comment]
Resolvido By Lenart
06.11.24
